import React, { useEffect, useState } from 'react';
import { Alert, Autocomplete, AppBar, Avatar, Box, Button, Chip, CircularProgress, Drawer, IconButton, InputAdornment, LinearProgress, List, ListItemButton, ListItemIcon, ListItemText, MenuItem, Paper, Snackbar, Stack, Tab, Tabs, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Toolbar, Tooltip, Typography } from '@mui/material';
import { LocalHospitalOutlined, Search, Close, Add, ChevronRight, Logout, Menu, Refresh, CheckCircleOutline, FilterList, EditOutlined, Inventory2Outlined, MedicationOutlined } from '@mui/icons-material';
import { modules, orderStatuses, type Module, type RecordData } from '@pharmacy/domain/admin';
import { api, money, date } from './api';
import { icons, groups, sectionFamilies, extras, title, fieldLabel, Status } from './common';
import Login from './Login';
import {InventoryForm,BatchDetails} from './InventoryForm';
import Overview from './Overview';
import { RecordEditor, StockDialog } from './Editor';
import Detail from './Detail';

import EditableDetails from './EditableDetails';
export default function App(){
 const [user,setUser]=useState<any>(null),[boot,setBoot]=useState(true),[section,setSection]=useState('overview'),[mobileMenu,setMobileMenu]=useState(false);
 const [overview,setOverview]=useState<any>(),[rows,setRows]=useState<RecordData[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[refs,setRefs]=useState<any>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editor,setEditor]=useState<{module:Module;record?:RecordData}|null>(null),[detail,setDetail]=useState<RecordData|null>(null),[stock,setStock]=useState<RecordData|null>(null);
 useEffect(()=>{const signout=()=>setUser(null);window.addEventListener('pharmacy:signout',signout);if(sessionStorage.getItem('pharmacy.admin.token'))api('/admin/me').then(setUser).catch(()=>{}).finally(()=>setBoot(false));else setBoot(false);return()=>window.removeEventListener('pharmacy:signout',signout);},[]);
 const [receiving,setReceiving]=useState(false);
 const [manufacturer,setManufacturer]=useState(''),[category,setCategory]=useState(''),[stockFilter,setStockFilter]=useState('');
 const module=modules.find(m=>m.key===section);const meta=module||extras[section];
 const allowed=(key:string)=>key==='overview'||(modules.find(m=>m.key===key)?.roles||(['orders','prescriptions','requests'].includes(key)?['admin','pharmacist','support']:['inventory','batches'].includes(key)?['admin','catalog']:['admin'])).includes(user?.role);
 const family=sectionFamilies.find(keys=>keys.includes(section));
 const activeSection=family?.[0]||section;
 const navigate=(key:string)=>{setSection(key==='inventory'?'products':key);setManufacturer('');setCategory('');setStockFilter(key==='inventory'?'low':'');setPage(0);setQuery('');setFilter('');setDetail(null);setMobileMenu(false);};
 async function load(){setBusy(true);setError('');try{const [o,r]=await Promise.all([api('/admin/overview'),api('/admin/reference')]);setOverview(o);setRefs(r);if(section!=='overview'){const c=section==='prescriptions'?'orders':section;const result=await api(`/admin/${c}?search=${encodeURIComponent(query)}&status=${encodeURIComponent(filter)}&page=${page}&limit=25${section==='prescriptions'?'&prescription=true':''}${section==='products'?'&manufacturer='+encodeURIComponent(manufacturer)+'&category='+encodeURIComponent(category)+'&stock='+stockFilter:''}`);setRows(result.items);setTotal(result.total);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(user){const timer=setTimeout(()=>{void load();},200);return()=>clearTimeout(timer);}},[user,section,page,query,filter,manufacturer,category,stockFilter]);
 const updated=(message:string)=>{setNotice(message);void load();};
 const saved=()=>{setEditor(null);setDetail(null);setStock(null);setNotice('Changes saved successfully.');void load();};
 if(boot)return <Box className="loading"><CircularProgress/></Box>;
 if(!user)return <Login onLogin={setUser}/>;
 const navigation=<Box className="sidebar-inner"><Stack direction="row" alignItems="center" spacing={1.5} className="brand"><Avatar sx={{bgcolor:'#0a6b58',borderRadius:2,width:43,height:43}}><LocalHospitalOutlined/></Avatar><Box><Typography fontWeight={750} fontSize={16}>Old City Pharmacy</Typography><Typography fontSize={10} letterSpacing={2} color="text.secondary">MANAGEMENT CONSOLE</Typography></Box></Stack><Box className="workspace-label"><span className="online-dot"/> Pharmacy workspace <Chip label={overview?.demoMode?'TEST':'LIVE'} size="small" sx={{ml:'auto',height:20,fontSize:9,bgcolor:'#edf2ef'}}/></Box><Box sx={{flex:1,overflowY:'auto',px:1.5}}>{groups.map(group=><Box key={group.title} sx={{mb:2}}><Typography className="nav-label">{group.title}</Typography><List disablePadding>{group.keys.filter(allowed).map(key=><ListItemButton key={key} selected={activeSection===key} onClick={()=>navigate(key)} sx={{borderRadius:2,mb:.35,py:.8,'&.Mui-selected':{bgcolor:'#e5f2ec',color:'primary.main'},'& .MuiListItemIcon-root':{minWidth:36,color:'inherit'}}}><ListItemIcon>{icons[key]}</ListItemIcon><ListItemText primary={key==='dosageForms'?'Master Data':title(key)} primaryTypographyProps={{fontSize:13,fontWeight:activeSection===key?700:500}}/>{key==='orders'&&overview?.openOrders>0&&<Chip size="small" label={overview.openOrders} sx={{height:20,bgcolor:'#daede3',color:'primary.main'}}/>}</ListItemButton>)}</List></Box>)}</Box><Box className="sidebar-footer"><Avatar sx={{bgcolor:'#e4eee9',color:'primary.main',width:34,height:34,fontSize:13}}>{user.name.slice(0,2).toUpperCase()}</Avatar><Box flex={1}><Typography fontSize={12} fontWeight={700}>{user.name}</Typography><Typography fontSize={11} color="text.secondary">{user.role}</Typography></Box><Tooltip title="Sign out"><IconButton aria-label="Sign out" onClick={async()=>{try{await api('/logout',{method:'POST'});}finally{sessionStorage.removeItem('pharmacy.admin.token');setUser(null);}}}><Logout fontSize="small"/></IconButton></Tooltip></Box></Box>;
 return <Box className="shell"><Box className="desktop-sidebar">{navigation}</Box><Drawer open={mobileMenu} onClose={()=>setMobileMenu(false)} sx={{'& .MuiDrawer-paper':{width:264}}}>{navigation}</Drawer><Box className="main"><AppBar position="static" elevation={0} color="transparent" sx={{bgcolor:'white',borderBottom:1,borderColor:'divider'}}><Toolbar sx={{gap:1.5,minHeight:'72px !important'}}><IconButton className="menu-toggle" aria-label="Open navigation" onClick={()=>setMobileMenu(true)}><Menu/></IconButton><Typography fontSize={13} color="text.secondary">Workspace</Typography><ChevronRight sx={{fontSize:16,color:'#a7b5b7'}}/><Typography fontSize={13} fontWeight={650}>{meta.title}</Typography><Box flex={1}/><Chip icon={<CheckCircleOutline/>} label="Shared app API" variant="outlined" color="primary" size="small"/><Tooltip title="Refresh data"><IconButton aria-label="Refresh data" onClick={()=>void load()}><Refresh/></IconButton></Tooltip><Avatar sx={{width:32,height:32,bgcolor:'#eaf1ee',color:'primary.main',fontSize:12}}>{user.name[0]}</Avatar></Toolbar></AppBar>{busy&&<LinearProgress sx={{height:2}}/>}<Box className="page"><Stack direction="row" justifyContent="space-between" alignItems="flex-start" gap={2} mb={3}><Box><Typography className="eyebrow">{section==='overview'?'YOUR PHARMACY, CONNECTED':'PHARMACY MANAGEMENT'}</Typography><Typography variant="h4" sx={{fontSize:{xs:27,md:32},mb:.8}}>{section==='overview'?'Workspace overview':meta.title}</Typography><Typography color="text.secondary" fontSize={13}>{meta.description}</Typography></Box>{module&&<Button variant="contained" startIcon={<Add/>} onClick={()=>section==='products'?setReceiving(true):setEditor({module})} disabled={section==='home'&&total>0}>Add {module.singular}</Button>}{section==='batches'&&<Button variant="contained" startIcon={<Add/>} onClick={()=>setReceiving(true)}>Receive medicine</Button>}{section==='inventory'&&<Button variant="contained" startIcon={<Add/>} onClick={()=>setStock({} as RecordData)}>Adjust stock</Button>}</Stack>{error&&<Alert severity="error" sx={{mb:2}} action={<Button onClick={()=>void load()}>Retry</Button>}>{error}</Alert>}{overview?.demoMode&&<Alert severity="info" icon={false} sx={{mb:3,bgcolor:'#edf4f8',py:.2,fontSize:12}}>Testing workspace · Sample data and prices. Changes are shared with the connected customer app.</Alert>}
 {family&&<Tabs value={section} onChange={(_,key)=>navigate(key)} variant="scrollable" scrollButtons="auto" sx={{mb:2,borderBottom:1,borderColor:'divider'}}>{family.filter(allowed).map(key=><Tab key={key} value={key} label={title(key)}/>)}</Tabs>}
 {section==='overview'&&overview?<Overview data={overview} navigate={navigate} allowed={allowed} onOrder={order=>{navigate('orders');setDetail(order);}}/>:section==='overview'?<CircularProgress/>:<Paper variant="outlined" sx={{overflow:'hidden'}}><Stack direction={{xs:'column',sm:'row'}} gap={2} p={2} alignItems={{sm:'center'}}><TextField placeholder={`Search ${meta.title.toLowerCase()}…`} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} slotProps={{input:{startAdornment:<InputAdornment position="start"><Search sx={{fontSize:19}}/></InputAdornment>,endAdornment:query?<InputAdornment position="end"><IconButton aria-label="Clear search" size="small" onClick={()=>{setQuery('');setPage(0);}}><Close fontSize="small"/></IconButton></InputAdornment>:undefined}}} sx={{minWidth:240,flex:1}}/>{(['orders','prescriptions','requests'].includes(section)||module?.fields.some(f=>f.key==='status'))&&<TextField select label="Filter" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}} sx={{minWidth:175}}><MenuItem value="">All records</MenuItem>{(section==='orders'||section==='prescriptions'?orderStatuses:section==='requests'?['New','Contacted','Sourcing','Closed']:['draft','published','archived']).map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField>}<Chip icon={<FilterList/>} variant="outlined" label={`${total} records`}/></Stack>{section==='products'&&<Stack direction={{xs:'column',md:'row'}} gap={2} px={2} pb={2}>
 <Autocomplete options={(refs.manufacturers||[]).map((m:any)=>m.name)} value={manufacturer||null} onChange={(_,v)=>{setManufacturer(v||'');setPage(0);}} clearText="Clear manufacturer" sx={{flex:1}} renderInput={params=><TextField {...params} label="Manufacturer" placeholder="All manufacturers"/>}/>
 <Autocomplete options={(refs.categories||[]).flatMap((c:any)=>[c.name,...c.subcategories]).filter((v:string,i:number,a:string[])=>a.indexOf(v)===i)} value={category||null} onChange={(_,v)=>{setCategory(v||'');setPage(0);}} clearText="Clear category" sx={{flex:1}} renderInput={params=><TextField {...params} label="Category / subcategory" placeholder="All categories"/>}/>
 <TextField select label="Stock availability" value={stockFilter} onChange={e=>{setStockFilter(e.target.value);setPage(0);}} sx={{minWidth:180}}><MenuItem value="">All stock</MenuItem><MenuItem value="available">In stock</MenuItem><MenuItem value="low">Low stock (10 or fewer)</MenuItem><MenuItem value="out">Out of stock</MenuItem></TextField>
 {(manufacturer||category||stockFilter||query||filter)&&<Button onClick={()=>{setManufacturer('');setCategory('');setStockFilter('');setQuery('');setFilter('');setPage(0);}}>Clear filters</Button>}
 </Stack>}<TableContainer><Table size="small"><TableHead><TableRow>{meta.columns.map(c=><TableCell key={c}>{fieldLabel(c,module)}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map(row=><TableRow key={row.id} hover tabIndex={0} aria-label={`Open ${row.brandName||row.name||row.title||row.id}`} onClick={()=>setDetail(row)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setDetail(row);}}} sx={{cursor:'pointer','&:focus-visible':{outline:'2px solid #0a6b58',outlineOffset:-2}}}>{meta.columns.map((c,i)=><TableCell key={c} sx={{maxWidth:260}}>{c==='status'||c==='followUp'||c==='review'?<Status value={row[c]||'Pending'}/>:c==='active'?<Status value={row[c]?'active':'inactive'}/>:c.endsWith('Paise')?money(row[c]||0):c==='stock'?<Chip label={`${row.stock??0} packs`} size="small" color={row.stock<=10?'warning':'default'} variant="outlined"/>:c==='date'||c.endsWith('At')?date(row[c]):<Stack direction="row" spacing={1.2} alignItems="center">{i===0&&section==='products'&&<Avatar src={row.image} variant="rounded" sx={{width:36,height:40,bgcolor:'#f3f7f5'}}><MedicationOutlined/></Avatar>}<Typography fontSize={12} fontWeight={i===0?650:400} sx={{overflowWrap:'anywhere'}}>{c==='id'&&['orders','prescriptions'].includes(section)?`Order ID: ${row.id}`:String(row[c]??'—')}</Typography></Stack>}</TableCell>)}</TableRow>)}{!rows.length&&!busy&&<TableRow><TableCell colSpan={meta.columns.length}><Box py={7} textAlign="center"><Box sx={{color:'#9aafaa',mb:1}}>{icons[section]}</Box><Typography fontWeight={650}>No records found</Typography><Typography variant="body2" color="text.secondary">{query||filter?'Try a different search or filter.':module?`Add your first ${module.singular} to get started.`:'New activity will appear here.'}</Typography></Box></TableCell></TableRow>}</TableBody></Table></TableContainer><TablePagination component="div" count={total} page={page} onPageChange={(_,p)=>setPage(p)} rowsPerPage={25} rowsPerPageOptions={[25]}/></Paper>}
 <Typography sx={{mt:3,fontSize:11,color:'#889a9d'}}>Old City Pharmacy · One workspace for your customer app and pharmacy team</Typography></Box></Box>
 {receiving&&<InventoryForm refs={refs} onClose={()=>setReceiving(false)} onSaved={()=>{setReceiving(false);saved();}}/>}{editor&&<RecordEditor {...editor} refs={refs} onClose={()=>setEditor(null)} onSaved={saved}/>} {detail&&(section==='batches'?<BatchDetails record={detail} role={user.role} onClose={()=>setDetail(null)} onSaved={saved}/>:section==='products'?<InventoryForm product={detail} refs={refs} onClose={()=>setDetail(null)} onSaved={saved}/>:module?<EditableDetails module={module} record={detail} refs={refs} onClose={()=>setDetail(null)} onUpdated={updated}/>:<Detail section={section} record={detail} refs={refs} role={user.role} onClose={()=>setDetail(null)} onSaved={saved}/>)} {stock&&<StockDialog record={stock} refs={refs} onClose={()=>setStock(null)} onSaved={saved}/>}<Snackbar anchorOrigin={{vertical:'top',horizontal:'right'}} open={!!notice} autoHideDuration={4000} onClose={()=>setNotice('')}><Alert severity="success" variant="filled">{notice}</Alert></Snackbar></Box>;
}
