import React from 'react';
import { Chip } from '@mui/material';
import { DashboardOutlined, MedicationOutlined, ShoppingBagOutlined, Inventory2Outlined, PeopleOutline, LocalHospitalOutlined, ReceiptLongOutlined, CameraAltOutlined, PlaceOutlined, CategoryOutlined, ApartmentOutlined, ArticleOutlined, ShieldOutlined, HistoryOutlined, HomeOutlined } from '@mui/icons-material';
import { modules, type Module } from '@pharmacy/domain/admin';
export const icons:Record<string,React.ReactNode>={batches:<Inventory2Outlined/>,dosageForms:<CategoryOutlined/>,overview:<DashboardOutlined/>,products:<MedicationOutlined/>,orders:<ShoppingBagOutlined/>,inventory:<Inventory2Outlined/>,customers:<PeopleOutline/>,doctors:<LocalHospitalOutlined/>,clinics:<PlaceOutlined/>,categories:<CategoryOutlined/>,manufacturers:<ApartmentOutlined/>,localities:<PlaceOutlined/>,specialties:<LocalHospitalOutlined/>,home:<HomeOutlined/>,pages:<ArticleOutlined/>,staff:<ShieldOutlined/>,audit:<HistoryOutlined/>,requests:<CameraAltOutlined/>,prescriptions:<ReceiptLongOutlined/>};
export const groups=[{title:'WORKSPACE',keys:['overview','orders','prescriptions','requests','customers']},{title:'CATALOG & CARE',keys:['products','batches','dosageForms','doctors','localities']},{title:'APP MANAGEMENT',keys:['home','pages','staff','audit']}];
export const extras:Record<string,{title:string;description:string;columns:string[]}>={batches:{title:'Medicine Inventory',description:'Traceable receipts, expiry dates and batch movements.',columns:['brandName','batchNumber','supplier','quantityReceived','quantityAvailable','expiryDate','pricePaise']},overview:{title:'Overview',description:'A clear view of your pharmacy, all in one place.',columns:[]},orders:{title:'Orders',description:'Review, confirm and track every customer order.',columns:['id','customerId','date','totalPaise','status']},prescriptions:{title:'Prescriptions',description:'Review private prescription attachments before confirmation.',columns:['id','customerId','date','review','status']},requests:{title:'Medicine requests',description:'Photo requests and pharmacy follow-up.',columns:['id','customerId','date','followUp','assignedTo']},inventory:{title:'Inventory ledger',description:'Every stock change, with its reason and balance.',columns:['productName','delta','balance','reason','createdAt']},audit:{title:'Activity log',description:'An auditable history of changes and authorized attachment access.',columns:['actor','action','collection','reason','createdAt']}};
export const title=(key:string)=>modules.find(m=>m.key===key)?.title||extras[key]?.title||key;
export const fieldLabel=(key:string,module?:Module)=>module?.fields.find(f=>f.key===key)?.label.replace(' (₹)','')||({id:'Order ID',customerId:'Customer',totalPaise:'Total',createdAt:'Date',updatedAt:'Updated',productName:'Product',followUp:'Follow-up',assignedTo:'Assigned to',pricePaise:'Selling price',manufacturerGroup:'Manufacturer',review:'Prescription review'} as Record<string,string>)[key]||key.replace(/([A-Z])/g,' $1');
export function Status({value}:{value:string}){const good=['published','Delivered','Approved','Closed','active'].includes(value);const bad=['Cancelled','Rejected','archived','inactive'].includes(value);return <Chip size="small" label={value} sx={{bgcolor:good?'#e6f4eb':bad?'#fdebe8':'#fff3dd',color:good?'#267b49':bad?'#b24538':'#9e6a12',borderRadius:1.5}}/>;}

export const sectionFamilies = [['doctors','clinics','specialties'],['dosageForms','manufacturers','categories','unitTypes','suppliers','drugSchedules','storageRequirements']];
