import React,{useEffect,useState} from 'react';
import {Alert,Avatar,Box,Button,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,MenuItem,Stack,Tab,Tabs,TextField,Typography} from '@mui/material';
import {Add,Close,FamilyRestroomOutlined,PersonOutline,DescriptionOutlined,PhoneOutlined,LocationOnOutlined,EditOutlined,UploadFileOutlined,ShoppingBagOutlined} from '@mui/icons-material';
import {modules,type RecordData} from '@pharmacy/domain/admin';
import {api,date,money} from './api';
import {RecordEditor} from './Editor';
import {Status} from './common';
export default function CustomerDetails({record,refs,onClose,onUpdated}:{record:RecordData;refs:any;onClose:()=>void;onUpdated:(message:string)=>void}){
 const [customer,setCustomer]=useState(record),[tab,setTab]=useState(0),[patients,setPatients]=useState<any[]>([]),[prescriptions,setPrescriptions]=useState<any[]>([]),[history,setHistory]=useState<any>(),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[patientEditor,setPatientEditor]=useState<any>(),[rxEditor,setRxEditor]=useState(false),[editAccount,setEditAccount]=useState(false),[photo,setPhoto]=useState('');
 async function load(){setLoading(true);setError('');try{const [family,h]=await Promise.all([api('/admin/customers/'+customer.id+'/patients'),api('/admin/customers/'+customer.id+'/history')]);setPatients(family.patients);setPrescriptions(family.prescriptions);setHistory(h);setSelected(id=>family.patients.some((p:any)=>p.id===id)?id:family.patients[0]?.id||'');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[customer.id]);
 const active=patients.find(p=>p.id===selected),records=prescriptions.filter(r=>r.patientId===selected);
 const saved=(message:string)=>{setPatientEditor(undefined);setRxEditor(false);void load();onUpdated(message);};
 return <><Dialog open fullWidth maxWidth="md" onClose={onClose} aria-label="Customer account" sx={{'& .MuiDialog-paper':{m:{xs:1,sm:4},width:{xs:'calc(100% - 16px)',sm:'calc(100% - 64px)'}}}}><DialogTitle component="div"><Stack direction="row" spacing={2} alignItems="center"><Avatar sx={{width:54,height:54,bgcolor:'primary.main'}}>{customer.name.slice(0,1)}</Avatar><Box flex={1} minWidth={0}><Typography variant="overline" color="primary" sx={{display:'block',lineHeight:1.5,mb:0.5}}>Household account</Typography><Typography variant="h5">{customer.name}</Typography><Typography variant="body2" color="text.secondary">{customer.phone} · {customer.locality}</Typography></Box><IconButton aria-label="Close customer" onClick={onClose}><Close/></IconButton></Stack></DialogTitle>
 <Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto" sx={{flexShrink:0,minHeight:56}}><Tab icon={<FamilyRestroomOutlined/>} iconPosition="start" label="Patients & prescriptions"/><Tab icon={<ShoppingBagOutlined/>} iconPosition="start" label="Orders"/><Tab icon={<PersonOutline/>} iconPosition="start" label="Account"/></Tabs>
 <DialogContent dividers>{error&&<Alert severity="error" action={<Button onClick={()=>void load()}>Retry</Button>} sx={{mb:2}}>{error}</Alert>}
 <Box className="detail-metrics" sx={{gridTemplateColumns:'repeat(3, minmax(0, 1fr))','& .detail-metric':{p:{xs:1,sm:2}},'& .MuiTypography-caption':{fontSize:{xs:10,sm:12}}}}>{[['Patients',patients.length],['Prescriptions',prescriptions.length],['Orders',history?.orders.length??'—']].map(([label,value])=><Box key={label} className="detail-metric"><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5">{value}</Typography></Box>)}</Box>
 {loading?<Box py={4} textAlign="center"><CircularProgress size={28}/></Box>:tab===0?<Stack gap={2}><Stack direction={{xs:'column',sm:'row'}} alignItems={{xs:'stretch',sm:'center'}} justifyContent="space-between" gap={1}><Box><Typography variant="h6">Family patients</Typography><Typography variant="body2" color="text.secondary">Separate profiles and prescriptions for everyone this account cares for.</Typography></Box><Button startIcon={<Add/>} variant="contained" onClick={()=>setPatientEditor({name:'',age:'',relationship:''})}>Add patient</Button></Stack>
 {!patients.length?<Box className="detail-section" textAlign="center" py={5}><FamilyRestroomOutlined sx={{fontSize:52,color:'primary.main',mb:1}}/><Typography fontWeight={700}>No patients added yet</Typography><Typography variant="body2" color="text.secondary">Add the account holder or a family member to save their prescriptions.</Typography></Box>:<><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:1.5}}>{patients.map(p=><Box key={p.id} component="button" type="button" onClick={()=>setSelected(p.id)} aria-pressed={selected===p.id} sx={{textAlign:'left',p:2,display:'flex',alignItems:'center',gap:1.5,cursor:'pointer',font:'inherit',borderRadius:3,border:'2px solid',borderColor:selected===p.id?'primary.main':'divider',bgcolor:selected===p.id?'primary.light':'white'}}><Avatar sx={{bgcolor:'white',color:'primary.main'}}><PersonOutline/></Avatar><Box flex={1}><Typography fontWeight={700}>{p.name}</Typography><Typography variant="body2" color="text.secondary">Age {p.age} · {p.relationship||'Patient'}</Typography></Box><Chip size="small" label={`${prescriptions.filter(r=>r.patientId===p.id).length} Rx`}/></Box>)}</Box>
 {active&&<Box className="detail-section"><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1.5} mb={2}><Box><Typography variant="h6">{active.name}'s prescriptions</Typography><Typography variant="caption" color="text.secondary">Age {active.age}, recorded {date(active.ageRecordedAt)}</Typography></Box><Stack direction="row" spacing={1}><Button startIcon={<EditOutlined/>} onClick={()=>setPatientEditor(active)}>Edit patient</Button><Button startIcon={<Add/>} variant="outlined" onClick={()=>setRxEditor(true)}>Add prescription</Button></Stack></Stack>
 {!records.length?<Box sx={{py:3,textAlign:'center',bgcolor:'#f7f9f8',borderRadius:2}}><DescriptionOutlined color="disabled"/><Typography color="text.secondary" variant="body2">No prescriptions saved for this patient.</Typography></Box>:<Stack gap={1.5}>{records.map(r=><Box key={r.id} sx={{border:1,borderColor:'divider',borderRadius:2,p:2}}><Stack direction="row" gap={1.5} alignItems="center"><Avatar variant="rounded" sx={{bgcolor:'primary.light',color:'primary.main'}}><DescriptionOutlined/></Avatar><Box flex={1}><Typography fontWeight={700}>{r.title}</Typography><Typography variant="body2" color="text.secondary">{r.prescribedDate}{r.doctorName?' · '+r.doctorName:''}</Typography></Box><Button onClick={async()=>{try{const image=await api('/admin/customers/'+customer.id+'/patients/'+active.id+'/prescriptions/'+r.id+'/photo');setPhoto(image.uri);}catch(e){setError((e as Error).message);}}}>View</Button></Stack>{r.notes&&<Typography variant="body2" mt={1.5} sx={{whiteSpace:'pre-wrap'}}>{r.notes}</Typography>}{r.orderId&&<Chip size="small" label={'Order ID: '+r.orderId} sx={{mt:1}}/>}<Typography display="block" variant="caption" color="text.secondary" mt={1}>Saved for {r.patientSnapshot.name} · Age {r.patientSnapshot.age}</Typography></Box>)}</Stack>}</Box>}</>}
 </Stack>:tab===1?<Stack spacing={2}><Typography variant="h6">Account order history</Typography><Typography variant="body2" color="text.secondary">Orders belong to the account. Patient prescriptions are linked explicitly, rather than assigned from the buyer's name.</Typography>{history?.orders.map((o:any)=><Box className="detail-section" key={o.id}><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography fontWeight={700}>Order ID: {o.id}</Typography><Typography variant="caption" color="text.secondary">{date(o.date)}</Typography></Box><Status value={o.status}/></Stack><Typography variant="body2" my={1.5}>{o.items.map((i:any)=>i.medicine.brandName+' × '+i.quantity).join(' · ')}</Typography><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>{money(o.totalPaise)}</Typography><Typography variant="caption" color="text.secondary">{prescriptions.filter(r=>r.orderId===o.id).length} linked patient prescriptions</Typography></Stack></Box>)}{!history?.orders.length&&<Typography color="text.secondary">No orders yet.</Typography>}</Stack>:<Stack gap={2}><Box className="detail-section"><Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}><Typography variant="h6">Account information</Typography><Button startIcon={<EditOutlined/>} onClick={()=>setEditAccount(true)}>Edit account</Button></Stack><Typography fontWeight={700}>{customer.name}</Typography><Stack direction="row" gap={1} my={1}><PhoneOutlined color="primary" fontSize="small"/><Typography>{customer.phone}</Typography></Stack><Status value={customer.active?'active':'inactive'}/></Box><Box className="detail-section"><Stack direction="row" spacing={1} mb={1}><LocationOnOutlined color="primary"/><Typography variant="h6">Delivery address</Typography></Stack><Typography>{customer.address}</Typography><Typography color="text.secondary">{customer.locality} · {customer.landmark}</Typography></Box><Box className="detail-section"><Typography variant="h6">Medicine requests</Typography>{history?.requests.map((r:any)=><Stack key={r.id} direction="row" justifyContent="space-between" py={1}><Typography variant="body2">{date(r.date)}</Typography><Status value={r.followUp||r.status}/></Stack>)}{!history?.requests.length&&<Typography color="text.secondary">No requests yet.</Typography>}</Box></Stack>}
 </DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>
 {patientEditor&&<PatientEditor customerId={customer.id} patient={patientEditor} onClose={()=>setPatientEditor(undefined)} onSaved={()=>saved('Patient details saved successfully.')}/>}
 {rxEditor&&active&&<PrescriptionEditor customerId={customer.id} patient={active} orders={history?.orders||[]} onClose={()=>setRxEditor(false)} onSaved={()=>saved('Prescription saved for '+active.name+'.')}/>}
 {editAccount&&<RecordEditor module={modules.find(m=>m.key==='customers')!} record={customer} refs={refs} onClose={()=>setEditAccount(false)} onSaved={async()=>{setEditAccount(false);try{const result=await api('/admin/customers?search='+customer.id);setCustomer(result.items.find((c:any)=>c.id===customer.id)||customer);onUpdated('Account details saved successfully.');}catch(e){setError((e as Error).message);}}}/>}
 <Dialog open={!!photo} onClose={()=>setPhoto('')} fullWidth maxWidth="md"><DialogTitle>Patient prescription</DialogTitle><DialogContent><Box component="img" src={photo} alt="Patient prescription" sx={{width:'100%',maxHeight:'70vh',objectFit:'contain'}}/></DialogContent><DialogActions><Button onClick={()=>setPhoto('')}>Close</Button></DialogActions></Dialog></>;
}
function PatientEditor({customerId,patient,onClose,onSaved}:{customerId:string;patient:any;onClose:()=>void;onSaved:()=>void}){
 const [name,setName]=useState(patient.name),[age,setAge]=useState(String(patient.age)),[relationship,setRelationship]=useState(patient.relationship),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog open fullWidth maxWidth="xs" onClose={busy?undefined:onClose}><Box component="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const data={name,age:Number(age),relationship};await api('/admin/customers/'+customerId+'/patients'+(patient.id?'/'+patient.id:''),{method:patient.id?'PUT':'POST',body:JSON.stringify(patient.id?{data,version:patient.version}:data)});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><DialogTitle>{patient.id?'Edit patient':'Add patient'}</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{error&&<Alert severity="error">{error}</Alert>}<TextField required label="Patient name" value={name} onChange={e=>setName(e.target.value)}/><TextField required label="Age (years)" type="number" value={age} onChange={e=>setAge(e.target.value)} slotProps={{htmlInput:{min:0,max:130,step:1}}}/><TextField label="Relationship (optional)" placeholder="Mother, father, self…" value={relationship} onChange={e=>setRelationship(e.target.value)}/></Stack></DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" variant="contained" disabled={busy}>Save patient</Button></DialogActions></Box></Dialog>;
}
function PrescriptionEditor({customerId,patient,orders,onClose,onSaved}:{customerId:string;patient:any;orders:any[];onClose:()=>void;onSaved:()=>void}){
 const [data,setData]=useState({title:'',prescribedDate:new Date().toISOString().slice(0,10),doctorName:'',notes:'',photoId:'',orderId:''}),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog open fullWidth maxWidth="sm" onClose={busy?undefined:onClose}><Box component="form" onSubmit={async e=>{e.preventDefault();if(!data.photoId){setError('Attach the prescription image.');return;}setBusy(true);setError('');try{await api('/admin/customers/'+customerId+'/patients/'+patient.id+'/prescriptions',{method:'POST',body:JSON.stringify({...data,orderId:data.orderId||undefined})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><DialogTitle>Add prescription for {patient.name}</DialogTitle><DialogContent><Stack gap={2} pt={1}>{error&&<Alert severity="error">{error}</Alert>}<Chip icon={<PersonOutline/>} label={patient.name+' · Age '+patient.age} sx={{alignSelf:'flex-start'}}/><TextField required label="Prescription title" placeholder="e.g. September consultation" value={data.title} onChange={e=>setData(d=>({...d,title:e.target.value}))}/><TextField required type="date" label="Prescription date" value={data.prescribedDate} slotProps={{inputLabel:{shrink:true}}} onChange={e=>setData(d=>({...d,prescribedDate:e.target.value}))}/><TextField label="Doctor (optional)" value={data.doctorName} onChange={e=>setData(d=>({...d,doctorName:e.target.value}))}/><TextField select label="Related order (optional)" value={data.orderId} onChange={e=>setData(d=>({...d,orderId:e.target.value}))}><MenuItem value="">No linked order</MenuItem>{orders.map(o=><MenuItem key={o.id} value={o.id}>Order ID: {o.id}</MenuItem>)}</TextField><TextField label="Notes (optional)" multiline minRows={2} value={data.notes} onChange={e=>setData(d=>({...d,notes:e.target.value}))}/><Button component="label" variant="outlined" startIcon={<UploadFileOutlined/>} disabled={busy}>{busy?'Please wait…':data.photoId?'Replace prescription image':'Upload prescription image'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const result=await api('/media?patientId='+patient.id,{method:'POST',body:form});setData(d=>({...d,photoId:result.id}));setPreview(result.uri);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></Button>{preview&&<Box component="img" src={preview} alt="Prescription preview" sx={{height:180,objectFit:'contain'}}/>}<Typography variant="caption" color="text.secondary">Private prescription · Saved only under this patient.</Typography></Stack></DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" variant="contained" disabled={busy}>Save prescription</Button></DialogActions></Box></Dialog>;
}

