import React,{useEffect,useState} from 'react';
import { Alert, Box, Button, DialogActions, Divider, Dialog, IconButton, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { Close, CameraAltOutlined } from '@mui/icons-material';
import { modules, orderStatuses,type RecordData } from '@pharmacy/domain/admin';
import { api, money, date } from './api';
import { Status,fieldLabel } from './common';
import { FieldInput } from './Editor';
export default function Detail({section,record,refs,role,onEdit,onStock,onClose,onSaved}:{section:string;record:RecordData;refs:any;role:string;onEdit?:()=>void;onStock?:()=>void;onClose:()=>void;onSaved:()=>void}){
 const order=section==='orders'||section==='prescriptions',request=section==='requests';
 const [status,setStatus]=useState(record.status),[review,setReview]=useState(record.review||'Pending'),[eta,setEta]=useState(record.eta||''),[notes,setNotes]=useState(record.notes||''),[followUp,setFollowUp]=useState(record.followUp||'New'),[assignedTo,setAssignedTo]=useState(record.assignedTo||''),[reason,setReason]=useState(''),[image,setImage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [history,setHistory]=useState<any>(),[historyError,setHistoryError]=useState('');
 const loadHistory=()=>{setHistoryError('');api('/admin/customers/'+record.id+'/history').then(setHistory).catch(e=>setHistoryError(e.message));};
 useEffect(()=>{if(section==='customers')loadHistory();},[section,record.id]);
 const module=modules.find(m=>m.key===section);
 const canEdit=(order&&['admin','pharmacist'].includes(role))||request;
 return <Dialog open fullWidth maxWidth="md" onClose={busy?undefined:onClose} aria-label="Record details"><Box component="form" sx={{display:'flex',flexDirection:'column',maxHeight:'85vh'}} onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/admin/'+(order?'orders':'requests')+'/'+record.id,{method:'PATCH',body:JSON.stringify(order?{status,review,eta,notes,reason,version:record.version}:{followUp,assignedTo,notes,reason,version:record.version})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Stack p={3} direction="row" justifyContent="space-between"><Typography variant="h5">{order?'Order ID: ':request?'Request ID: ':''}{order||request?record.id:(record.brandName||record.name||record.title||'Record details')}</Typography><IconButton aria-label="Close details" onClick={onClose}><Close/></IconButton></Stack><Divider/><Stack spacing={2.5} p={3} sx={{overflowY:'auto',flex:1}}>{error&&<Alert severity="error">{error}</Alert>}{order&&<><Status value={record.status}/><Typography variant="body2">{date(record.date)}</Typography><Paper variant="outlined" sx={{p:2}}><Typography fontWeight={700}>{record.delivery.name}</Typography><Typography variant="body2">{record.phone||'No phone snapshot'}<br/>{record.delivery.address}, {record.delivery.locality}<br/>{record.delivery.landmark}</Typography></Paper>{record.items.map((item:any)=><Stack key={item.medicine.id} direction="row" justifyContent="space-between" spacing={2}><Box><Typography fontSize={13} fontWeight={650}>{item.medicine.brandName} × {item.quantity}</Typography><Typography variant="caption">{item.medicine.packageSize}</Typography></Box><Typography variant="body2">{money(Math.round(item.medicine.price*100)*item.quantity)}</Typography></Stack>)}<Divider/><Stack direction="row" justifyContent="space-between"><Typography variant="body2">Delivery contribution</Typography><Typography variant="body2">{money((record.deliveryContribution??0)*100)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>Total</Typography><Typography fontWeight={700}>{money(record.totalPaise)}</Typography></Stack><Box><Typography fontWeight={700} mb={1}>Timeline</Typography>{record.timeline.map((t:any,i:number)=><Typography key={i} variant="body2" color="text.secondary" mb={.5}>{t.status} · {date(t.date)}</Typography>)}</Box></>}
 {request&&<><Typography variant="body2">Customer: {record.customerId} · {date(record.date)}</Typography><Status value="Received"/>{record.demo&&!record.photoId&&<Alert severity="info">Seeded sample request. No medical photo is stored for this example.</Alert>}</>}
 {(record.prescriptionId||record.photoId)&&<><Button startIcon={<CameraAltOutlined/>} variant="outlined" onClick={async()=>{try{const photo=await api('/admin/media/'+(record.prescriptionId||record.photoId));setImage(photo.uri);}catch(e){setError((e as Error).message);}}}>Open private photo</Button>{image&&<Box component="img" src={image} alt="Submitted customer photo" sx={{maxWidth:'100%',maxHeight:450,objectFit:'contain'}}/>}</>}
 {canEdit&&order&&<><TextField select label="Order status" value={status} onChange={e=>setStatus(e.target.value)}>{orderStatuses.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField>{record.prescriptionSubmitted&&<TextField select label="Prescription review" value={review} onChange={e=>setReview(e.target.value)}>{['Pending','Approved','Rejected'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField>}<TextField label="Estimated delivery" value={eta} onChange={e=>setEta(e.target.value)}/></>}
 {request&&<><TextField select label="Internal follow-up" value={followUp} onChange={e=>setFollowUp(e.target.value)}>{['New','Contacted','Sourcing','Closed'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><FieldInput field={{key:'assignedTo',label:'Assigned staff',type:'select',reference:'staff'}} value={assignedTo} onChange={setAssignedTo} refs={refs}/></>}
 {canEdit&&<><TextField label="Internal notes" multiline minRows={3} value={notes} onChange={e=>setNotes(e.target.value)} helperText="Never shown in the customer app."/><TextField label="Reason for update" required value={reason} onChange={e=>setReason(e.target.value)}/></>}
 {!order&&!request&&<Box>{(record.image||record.photo)&&<Box component="img" src={record.image||record.photo} alt={record.brandName||record.name||'Record image'} sx={{maxHeight:160,maxWidth:'100%',objectFit:'contain',mb:2}}/>}<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:2}}>{Object.entries(record).filter(([key])=>module?module.fields.some(f=>f.key===key&&f.type!=='password'):!['id','version','before','after','passwordHash'].includes(key)).map(([key,value])=><Box key={key} mb={2}><Typography variant="caption" color="text.secondary">{fieldLabel(key,module)}</Typography><Typography variant="body2" sx={{overflowWrap:'anywhere'}}>{key.endsWith('Paise')?money(Number(value)):typeof value==='boolean'?(value?'Yes':'No'):typeof value==='object'?JSON.stringify(value):String(value)}</Typography></Box>)}</Box>{section==='audit'&&<><Typography fontWeight={700}>Change details</Typography>{['before','after'].map(key=><Box key={key}><Typography variant="caption">{key}</Typography><Box component="pre" sx={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:11,bgcolor:'#f6f8f8',p:1.5}}>{JSON.stringify(record[key],null,2)}</Box></Box>)}</>}</Box>}{section==='customers'&&<Box><Typography variant="h6">Order history</Typography>{historyError&&<Alert severity="error" action={<Button onClick={loadHistory}>Retry</Button>}>{historyError}</Alert>}{!history&&!historyError&&<Typography>Loading history…</Typography>}{history?.orders.length===0&&<Typography color="text.secondary">No orders yet.</Typography>}{history?.orders.map((o:any)=><Paper variant="outlined" key={o.id} sx={{p:2,mt:1.5}}><Stack direction="row" justifyContent="space-between" gap={2}><Typography fontWeight={700}>Order ID: {o.id}</Typography><Status value={o.status}/></Stack><Typography variant="body2" color="text.secondary">{date(o.date)}</Typography>{o.items.map((item:any)=><Typography key={item.medicine.id} variant="body2">{item.medicine.brandName} × {item.quantity}</Typography>)}<Typography fontWeight={700} mt={1}>{money(o.totalPaise)}</Typography></Paper>)}<Typography variant="h6" mt={3}>Medicine requests</Typography>{history?.requests.length===0&&<Typography color="text.secondary">No medicine requests yet.</Typography>}{history?.requests.map((r:any)=><Typography key={r.id} variant="body2" mt={1}>{date(r.date)} · {r.followUp||r.status}</Typography>)}</Box>}</Stack><Divider/><DialogActions><Button onClick={onClose}>Close</Button>{onStock&&<Button onClick={onStock}>Adjust stock</Button>}{onEdit&&<Button variant="contained" onClick={onEdit}>Edit details</Button>}{canEdit&&<Button type="submit" variant="contained" disabled={busy}>{busy?'Saving…':'Save update'}</Button>}</DialogActions></Box></Dialog>;
}
