import React,{useState} from 'react';
import { Alert, Box, Button, DialogActions, Divider, Drawer, IconButton, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { Close, CameraAltOutlined } from '@mui/icons-material';
import { orderStatuses,type RecordData } from '@pharmacy/domain/admin';
import { api, money, date } from './api';
import { Status,fieldLabel } from './common';
import { FieldInput } from './Editor';
export default function Detail({section,record,refs,role,onClose,onSaved}:{section:string;record:RecordData;refs:any;role:string;onClose:()=>void;onSaved:()=>void}){
 const order=section==='orders'||section==='prescriptions',request=section==='requests';
 const [status,setStatus]=useState(record.status),[review,setReview]=useState(record.review||'Pending'),[eta,setEta]=useState(record.eta||''),[notes,setNotes]=useState(record.notes||''),[followUp,setFollowUp]=useState(record.followUp||'New'),[assignedTo,setAssignedTo]=useState(record.assignedTo||''),[reason,setReason]=useState(''),[image,setImage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const canEdit=(order&&['admin','pharmacist'].includes(role))||request;
 return <Drawer open anchor="right" onClose={onClose} sx={{'& .MuiDrawer-paper':{width:{xs:'100%',sm:640}}}}><Box component="form" sx={{display:'flex',flexDirection:'column',height:'100%'}} onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/admin/'+(order?'orders':'requests')+'/'+record.id,{method:'PATCH',body:JSON.stringify(order?{status,review,eta,notes,reason,version:record.version}:{followUp,assignedTo,notes,reason,version:record.version})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Stack p={3} direction="row" justifyContent="space-between"><Typography variant="h5">{order?'Order ID: ':request?'Request ID: ':'Record: '}{record.id}</Typography><IconButton aria-label="Close details" onClick={onClose}><Close/></IconButton></Stack><Divider/><Stack spacing={2.5} p={3} sx={{overflowY:'auto',flex:1}}>{error&&<Alert severity="error">{error}</Alert>}{order&&<><Status value={record.status}/><Typography variant="body2">{date(record.date)}</Typography><Paper variant="outlined" sx={{p:2}}><Typography fontWeight={700}>{record.delivery.name}</Typography><Typography variant="body2">{record.phone||'No phone snapshot'}<br/>{record.delivery.address}, {record.delivery.locality}<br/>{record.delivery.landmark}</Typography></Paper>{record.items.map((item:any)=><Stack key={item.medicine.id} direction="row" justifyContent="space-between" spacing={2}><Box><Typography fontSize={13} fontWeight={650}>{item.medicine.brandName} × {item.quantity}</Typography><Typography variant="caption">{item.medicine.packageSize}</Typography></Box><Typography variant="body2">{money(Math.round(item.medicine.price*100)*item.quantity)}</Typography></Stack>)}<Divider/><Stack direction="row" justifyContent="space-between"><Typography variant="body2">Delivery contribution</Typography><Typography variant="body2">{money((record.deliveryContribution??0)*100)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>Total</Typography><Typography fontWeight={700}>{money(record.totalPaise)}</Typography></Stack><Box><Typography fontWeight={700} mb={1}>Timeline</Typography>{record.timeline.map((t:any,i:number)=><Typography key={i} variant="body2" color="text.secondary" mb={.5}>{t.status} · {date(t.date)}</Typography>)}</Box></>}
 {request&&<><Typography variant="body2">Customer: {record.customerId} · {date(record.date)}</Typography><Status value="Received"/>{record.demo&&!record.photoId&&<Alert severity="info">Seeded sample request. No medical photo is stored for this example.</Alert>}</>}
 {(record.prescriptionId||record.photoId)&&<><Button startIcon={<CameraAltOutlined/>} variant="outlined" onClick={async()=>{try{const photo=await api('/admin/media/'+(record.prescriptionId||record.photoId));setImage(photo.uri);}catch(e){setError((e as Error).message);}}}>Open private photo</Button>{image&&<Box component="img" src={image} alt="Submitted customer photo" sx={{maxWidth:'100%',maxHeight:450,objectFit:'contain'}}/>}</>}
 {canEdit&&order&&<><TextField select label="Order status" value={status} onChange={e=>setStatus(e.target.value)}>{orderStatuses.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField>{record.prescriptionSubmitted&&<TextField select label="Prescription review" value={review} onChange={e=>setReview(e.target.value)}>{['Pending','Approved','Rejected'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField>}<TextField label="Estimated delivery" value={eta} onChange={e=>setEta(e.target.value)}/></>}
 {request&&<><TextField select label="Internal follow-up" value={followUp} onChange={e=>setFollowUp(e.target.value)}>{['New','Contacted','Sourcing','Closed'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><FieldInput field={{key:'assignedTo',label:'Assigned staff',type:'select',reference:'staff'}} value={assignedTo} onChange={setAssignedTo} refs={refs}/></>}
 {canEdit&&<><TextField label="Internal notes" multiline minRows={3} value={notes} onChange={e=>setNotes(e.target.value)} helperText="Never shown in the customer app."/><TextField label="Reason for update" required value={reason} onChange={e=>setReason(e.target.value)}/></>}
 {!order&&!request&&<Box>{Object.entries(record).filter(([key])=>!['id','version','before','after'].includes(key)).map(([key,value])=><Box key={key} mb={2}><Typography variant="caption" color="text.secondary">{fieldLabel(key)}</Typography><Typography variant="body2" sx={{overflowWrap:'anywhere'}}>{typeof value==='object'?JSON.stringify(value):String(value)}</Typography></Box>)}{section==='audit'&&<><Typography fontWeight={700}>Change details</Typography>{['before','after'].map(key=><Box key={key}><Typography variant="caption">{key}</Typography><Box component="pre" sx={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:11,bgcolor:'#f6f8f8',p:1.5}}>{JSON.stringify(record[key],null,2)}</Box></Box>)}</>}</Box>}</Stack><Divider/><DialogActions><Button onClick={onClose}>Close</Button>{canEdit&&<Button type="submit" variant="contained" disabled={busy}>{busy?'Saving…':'Save update'}</Button>}</DialogActions></Box></Drawer>;
}
