import React,{useState} from 'react';
import {Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Alert,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,Paper,Stack,TextField,Typography} from '@mui/material';
import Close from '@mui/icons-material/Close';
import {orderStatuses,type Field,type RecordData} from '@pharmacy/domain/admin';
import {api,date,money} from './api';
import {Status,fieldLabel} from './common';
import {InlineField} from './InlineField';
export default function Detail({section,record,refs,role,onClose,onSaved}:{section:string;record:RecordData;refs:any;role:string;onClose:()=>void;onSaved:()=>void}){
 const order=section==='orders'||section==='prescriptions',request=section==='requests';
 const initial=()=>order?{status:record.status,review:record.review||'Not required',eta:record.eta||'',notes:record.notes||''}:{followUp:record.followUp||'New',assignedTo:record.assignedTo||'',notes:record.notes||''};
 const [draft,setDraft]=useState<any>(initial),[active,setActive]=useState<string[]>([]),[reason,setReason]=useState(''),[image,setImage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const editable=(order&&['admin','pharmacist'].includes(role))||request;
 const fields:Field[]=order?[{key:'status',label:'Order status',type:'select',choices:orderStatuses},...(record.prescriptionSubmitted?[{key:'review',label:'Prescription review',type:'select' as const,choices:['Pending','Approved','Rejected']}]:[]),{key:'eta',label:'Estimated delivery'},{key:'notes',label:'Internal notes',type:'textarea'}]:[{key:'followUp',label:'Internal follow-up',type:'select',choices:['New','Contacted','Sourcing','Closed']},{key:'assignedTo',label:'Assigned staff',type:'select',reference:'staff'},{key:'notes',label:'Internal notes',type:'textarea'}];
 return <Dialog open fullWidth maxWidth="md" onClose={busy?undefined:onClose} aria-label="Record details"><Box component="form" sx={{display:'flex',flexDirection:'column',maxHeight:'88vh'}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/admin/'+(order?'orders':'requests')+'/'+record.id,{method:'PATCH',body:JSON.stringify({...draft,version:record.version,reason})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <DialogTitle component="div"><Stack direction="row" justifyContent="space-between"><Typography variant="h5">{order?'Order ID: ':request?'Request ID: ':'Record: '}{record.id}</Typography><IconButton aria-label="Close details" onClick={onClose} disabled={busy}><Close/></IconButton></Stack>{editable&&<Typography variant="body2" color="text.secondary">Double-click a field to edit, or focus it and press Enter.</Typography>}</DialogTitle>
 <DialogContent dividers><Stack spacing={2}>{error&&<Alert severity="error">{error}</Alert>}
 {order&&<><Stack direction="row" justifyContent="space-between" alignItems="center"><Status value={record.status}/><Typography variant="body2" color="text.secondary">{date(record.date)}</Typography></Stack><Box className="detail-metrics">{[['Order total',money(record.totalPaise)],['Delivery contribution',money((record.deliveryContribution??0)*100)],['Items',record.items.reduce((sum:number,item:any)=>sum+item.quantity,0)]].map(([label,value])=><Box className="detail-metric" key={label}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6">{value}</Typography></Box>)}</Box><Box className="detail-section"><Typography variant="h6">Customer & delivery</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={3}><Box sx={{flex:1}}><Typography fontWeight={700}>{record.delivery.name}</Typography><Typography color="text.secondary" variant="body2">{record.phone||'No phone snapshot'}</Typography></Box><Box sx={{flex:2}}><Typography variant="body2">{record.delivery.address}, {record.delivery.locality}</Typography><Typography variant="body2" color="text.secondary">{record.delivery.landmark}</Typography></Box></Stack></Box><Box className="detail-section"><Typography variant="h6">Order items</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>Product</TableCell><TableCell align="center">Quantity</TableCell><TableCell align="right">Amount</TableCell></TableRow></TableHead><TableBody>{record.items.map((item:any)=><TableRow key={item.medicine.id}><TableCell><Typography fontWeight={600} variant="body2">{item.medicine.brandName}</Typography><Typography variant="caption" color="text.secondary">{item.medicine.packageSize}</Typography></TableCell><TableCell align="center">{item.quantity}</TableCell><TableCell align="right" sx={{whiteSpace:'nowrap',fontWeight:600}}>{money(Math.round(item.medicine.price*100)*item.quantity)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box><Box className="detail-section"><Typography variant="h6">Order timeline</Typography>{record.timeline.map((t:any,i:number)=><Box key={i} sx={{borderLeft:'2px solid',borderColor:'primary.light',pl:2,pb:2,position:'relative','&:before':{content:'""',position:'absolute',width:8,height:8,borderRadius:'50%',bgcolor:'primary.main',left:-5,top:6}}}><Typography fontWeight={600} variant="body2">{t.status}</Typography><Typography variant="caption" color="text.secondary">{date(t.date)}</Typography></Box>)}</Box></>}

 {request&&<><Typography>Customer: {record.customerId} · {date(record.date)}</Typography><Status value="Received"/>{!record.photoId&&<Alert severity="info">Sample request with no stored photo.</Alert>}</>}
 {(record.prescriptionId||record.photoId)&&<><Button variant="outlined" onClick={async()=>{try{const photo=await api('/admin/media/'+(record.prescriptionId||record.photoId));setImage(photo.uri);}catch(e){setError((e as Error).message);}}}>Open private photo</Button>{image&&<Box component="img" src={image} alt="Submitted customer photo" sx={{maxHeight:450,maxWidth:'100%',objectFit:'contain'}}/>}</>}
 {(order||request)&&<Box className="detail-section"><Typography variant="h6">{order?'Fulfillment':'Request follow-up'}</Typography><Box className="detail-fields">{fields.map(field=><InlineField key={field.key} field={field} value={draft[field.key]} refs={refs} editing={active.includes(field.key)} disabled={!editable||busy} onEdit={()=>setActive(old=>[...old,field.key])} onChange={value=>setDraft((old:any)=>({...old,[field.key]:value}))}/>)}</Box></Box>}
 {!order&&!request&&Object.entries(record).filter(([key])=>!['id','version','passwordHash'].includes(key)).map(([key,value])=><Box key={key}><Typography variant="caption">{fieldLabel(key)}</Typography><Typography component="pre" sx={{fontSize:12,whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{typeof value==='object'?JSON.stringify(value,null,2):String(value)}</Typography></Box>)}
 </Stack></DialogContent><DialogActions sx={{p:2,gap:1,flexWrap:'wrap'}}>{editable&&active.length>0&&<TextField label="Reason for change" required value={reason} onChange={e=>setReason(e.target.value)} sx={{flex:1}}/>}{editable?<><Button disabled={busy} onClick={()=>{setDraft(initial());setActive([]);setReason('');setError('');}}>Cancel</Button><Button type="submit" variant="contained" disabled={busy||JSON.stringify(draft)===JSON.stringify(initial())}>{busy?'Saving…':'Save changes'}</Button></>:<Button onClick={onClose}>Close</Button>}</DialogActions></Box></Dialog>;
}
