import React,{useEffect,useState} from 'react';
import {Avatar,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Alert,Box,Button,Dialog,DialogTitle,DialogContent,DialogActions,IconButton,Paper,Stack,TextField,Typography} from '@mui/material';
import Close from '@mui/icons-material/Close';
import type {Module,RecordData} from '@pharmacy/domain/admin';
import {api,date,money} from './api';
import {InlineField} from './InlineField';
const pick=(module:Module,row:RecordData)=>Object.fromEntries(module.fields.map(f=>[f.key,row[f.key]??(f.type==='boolean'?false:f.type==='multi'||f.type==='tags'?[]:'')]));
export default function EditableDetails({module,record,refs,onClose,onUpdated}:{module:Module;record:RecordData;refs:any;onClose:()=>void;onUpdated:(message:string)=>void}){
 const [current,setCurrent]=useState(record),[draft,setDraft]=useState(pick(module,record)),[active,setActive]=useState<string[]>([]),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<any>();
 useEffect(()=>{if(module.key==='customers')api('/admin/customers/'+record.id+'/history').then(setHistory).catch(e=>setError(e.message));},[module.key,record.id]);
 const cancel=()=>{setDraft(pick(module,current));setActive([]);setReason('');setError('');};
 const dirty=JSON.stringify(draft)!==JSON.stringify(pick(module,current));
 return <Dialog open fullWidth maxWidth="md" onClose={busy?undefined:onClose} aria-label="Record details"><Box component="form" sx={{display:'flex',flexDirection:'column',maxHeight:'88vh'}} onSubmit={async e=>{e.preventDefault();if(!dirty)return;setBusy(true);setError('');try{const saved=await api('/admin/'+module.key+'/'+current.id,{method:'PUT',body:JSON.stringify({data:draft,version:current.version,reason})});setCurrent(saved);setDraft(pick(module,saved));setActive([]);setReason('');onUpdated(module.singular[0].toUpperCase()+module.singular.slice(1)+' changes saved successfully.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <DialogTitle component="div"><Stack direction="row" justifyContent="space-between"><Stack direction="row" spacing={2} alignItems="center"><Avatar sx={{bgcolor:"primary.main",width:48,height:48}}>{String(current.name||current.title||current.shopName||module.title).slice(0,1)}</Avatar><Box><Typography variant="overline" color="primary">{module.singular}</Typography><Typography variant="h5">{current.name||current.title||current.shopName||module.title}</Typography></Box></Stack><IconButton aria-label="Close details" onClick={onClose} disabled={busy}><Close/></IconButton></Stack><Typography variant="body2" color="text.secondary">Double-click a field to edit, or focus it and press Enter. Changes are applied only when you save.</Typography></DialogTitle>
 <DialogContent dividers>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Box className="detail-section"><Typography variant="h6">{module.key==='customers'?'Account & delivery information':'Details'}</Typography><Box className="detail-fields">{module.fields.map(field=><Box key={field.key} sx={{gridColumn:field.type==='sections'||field.type==='textarea'?'1 / -1':undefined}}><InlineField field={field} value={draft[field.key]} refs={refs} editing={active.includes(field.key)} disabled={busy} onEdit={()=>setActive(keys=>[...keys,field.key])} onChange={v=>setDraft(old=>({...old,[field.key]:v}))}/></Box>)}</Box></Box>
 {module.key==='customers'&&<Box mt={3}><Box className="detail-metrics">{[['Orders',history?.orders.length??'—'],['Total ordered',history?money(history.orders.reduce((sum:number,o:any)=>sum+o.totalPaise,0)):'—'],['Medicine requests',history?.requests.length??'—']].map(([label,value])=><Box className="detail-metric" key={label}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6">{value}</Typography></Box>)}</Box><Box className="detail-section"><Typography variant="h6">Order history</Typography>{!history&&<Typography color="text.secondary">{error?'History could not be loaded.':'Loading history…'}</Typography>}<TableContainer><Table size="small"><TableHead><TableRow>{['Order / date','Items','Status','Total'].map(label=><TableCell key={label}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{history?.orders.map((order:any)=><TableRow key={order.id}><TableCell><Typography fontWeight={700}>Order ID: {order.id}</Typography><Typography variant="caption" color="text.secondary">{date(order.date)}</Typography></TableCell><TableCell>{order.items.map((item:any)=><Typography key={item.medicine.id} variant="body2">{item.medicine.brandName} × {item.quantity}</Typography>)}</TableCell><TableCell>{order.status}</TableCell><TableCell sx={{whiteSpace:'nowrap',fontWeight:700}}>{money(order.totalPaise)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>{history?.orders.length===0&&<Typography py={3} color="text.secondary">No orders yet.</Typography>}</Box><Box className="detail-section" mt={2}><Typography variant="h6">Medicine requests</Typography>{history?.requests.map((r:any)=><Stack key={r.id} direction="row" justifyContent="space-between" sx={{py:1.5,borderBottom:'1px solid',borderColor:'divider'}}><Typography variant="body2">{date(r.date)}</Typography><Typography variant="body2" fontWeight={600}>{r.followUp||r.status}</Typography></Stack>)}{history?.requests.length===0&&<Typography color="text.secondary">No requests yet.</Typography>}</Box></Box>}

 </DialogContent><DialogActions sx={{p:2,gap:1,flexWrap:'wrap'}}>{active.length>0&&<TextField label="Reason for change" required value={reason} onChange={e=>setReason(e.target.value)} disabled={busy} sx={{flex:1,minWidth:200}}/>}<Button disabled={busy} onClick={cancel}>Cancel</Button><Button type="submit" variant="contained" disabled={busy||!dirty}>{busy?'Saving…':'Save changes'}</Button></DialogActions></Box></Dialog>;
}
