import React,{useState} from 'react';
import { Alert, Autocomplete, Box, Button, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Drawer, FormControlLabel, IconButton, Paper, Stack, TextField, Typography } from '@mui/material';
import { Add, Close, UploadFileOutlined } from '@mui/icons-material';
import { type Field,type Module,type RecordData } from '@pharmacy/domain/admin';
import { api, money, date } from './api';
export function FieldInput({field,value,onChange,refs}:{field:Field;value:any;onChange:(v:any)=>void;refs:any}){
 const f=field;const [uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState('');
 const options=f.choices||(f.reference==='subcategories'?(refs.categories??[]).flatMap((c:any)=>c.subcategories):((refs[f.reference||'']??[]).map((r:any)=>['products','clinics','staff'].includes(f.reference||'')?r.id:r.name)))||[];
 const name=(value:string)=>['products','clinics','staff'].includes(f.reference||'')?(refs[f.reference!]?.find((r:any)=>r.id===value)?.name||value):value;
 if(f.type==='boolean')return <FormControlLabel control={<Checkbox checked={!!value} onChange={e=>onChange(e.target.checked)}/>} label={f.label}/>;
 if(f.type==='select'||f.type==='multi'||f.type==='tags')return <Autocomplete clearText="Clear search" sx={{'& .MuiAutocomplete-clearIndicator':{visibility:'visible'}}} multiple={f.type!=='select'} freeSolo={f.type==='tags'} options={options} getOptionLabel={name} value={value??(f.type==='select'?null:[])} onChange={(_,v)=>onChange(v??'')} renderInput={params=><TextField {...params} label={f.label} required={f.required&&(!value||!value.length)} helperText={f.type==='tags'?'Type a value and press Enter.':f.type==='multi'?'Select in the order you want them displayed.':f.help}/>}/>;
 if(f.type==='sections')return <Box><Typography fontSize={13} fontWeight={700} mb={1}>{f.label}</Typography>{(value||[]).map((section:string[],i:number)=><Paper key={i} variant="outlined" sx={{p:1.5,mb:1.5}}><Stack gap={1.5}><TextField label="Section heading" required value={section[0]} onChange={e=>onChange(value.map((v:any,j:number)=>j===i?[e.target.value,v[1]]:v))}/><TextField label="Section text" required multiline minRows={3} value={section[1]} onChange={e=>onChange(value.map((v:any,j:number)=>j===i?[v[0],e.target.value]:v))}/><Button color="error" size="small" onClick={()=>onChange(value.filter((_:any,j:number)=>j!==i))}>Remove section</Button></Stack></Paper>)}<Button startIcon={<Add/>} onClick={()=>onChange([...(value||[]),['','']])}>Add section</Button></Box>;
 if(f.type==='image')return <Box><TextField fullWidth label={f.label} required={f.required} value={value||''} onChange={e=>onChange(e.target.value)} helperText="Upload an image or enter its HTTPS URL."/>{value&&<Box component="img" src={value} alt="Image preview" sx={{width:100,height:100,objectFit:'contain',mt:1,border:1,borderColor:'divider',borderRadius:1}}/>}<Button component="label" disabled={uploading} startIcon={<UploadFileOutlined/>} sx={{ml:1}}>{uploading?'Uploading…':'Upload image'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setUploadError('');try{const form=new FormData();form.append('file',file);const result=await api('/media?public=true',{method:'POST',body:form});onChange(result.uri);}catch(e){setUploadError((e as Error).message);}finally{setUploading(false);}}}/></Button>{uploadError&&<Alert severity="error">{uploadError}</Alert>}</Box>;
 return <TextField fullWidth label={f.label} required={f.required} type={f.type==='money'||f.type==='number'?'number':f.type==='date'?'date':f.type==='password'?'password':'text'} multiline={f.type==='textarea'} minRows={f.type==='textarea'?3:undefined} value={f.type==='money'?(value===undefined?'':value/100):value??''} onChange={e=>onChange(f.type==='money'?Math.round(Number(e.target.value)*100):f.type==='number'?Number(e.target.value):e.target.value)} slotProps={{inputLabel:f.type==='date'?{shrink:true}:undefined,htmlInput:f.type==='money'?{min:0,step:.01}:f.type==='number'?{min:0,step:1}:undefined}} helperText={f.help}/>;
}
export function RecordEditor({module,record,refs,onClose,onSaved}:{module:Module;record?:RecordData;refs:any;onClose:()=>void;onSaved:()=>void}){
 const [data,setData]=useState<any>(()=>Object.fromEntries(module.fields.map(f=>[f.key,record?.[f.key]??(f.type==='boolean'?true:f.type==='multi'||f.type==='tags'?[]:f.type==='sections'?[['','']]:f.type==='number'||f.type==='money'?0:f.key==='status'?'draft':'')]))),[why,setWhy]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<any>();
 return <Dialog open fullWidth maxWidth="sm" onClose={busy?undefined:onClose} aria-label="Record editor"><Box component="form" sx={{maxHeight:'85vh',display:'flex',flexDirection:'column'}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/admin/'+module.key+(record?'/'+record.id:''),{method:record?'PUT':'POST',body:JSON.stringify({data,version:record?.version,reason:why})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Stack direction="row" alignItems="center" justifyContent="space-between" p={3}><Box><Typography className="eyebrow">{record?'EDIT RECORD':'NEW RECORD'}</Typography><Typography variant="h5">{record?(record.brandName||record.name||record.title||module.title):`Add ${module.singular}`}</Typography></Box><IconButton aria-label="Close editor" onClick={onClose} disabled={busy}><Close/></IconButton></Stack><Divider/><Stack spacing={2.5} sx={{p:3,overflowY:'auto',flex:1}}>{error&&<Alert severity="error">{error}</Alert>}{module.key==='products'&&<Alert severity="info">Selling price {money(data.pricePaise||0)} · {data.mrpPaise>data.pricePaise?(((data.mrpPaise-data.pricePaise)/data.mrpPaise)*100).toFixed(2)+'% OFF':'No discount'}. Stock is managed separately in Inventory.</Alert>}{module.key==='home'&&<Paper variant="outlined" sx={{p:2,bgcolor:'#eaf4ef'}}><Typography variant="caption">CUSTOMER PREVIEW</Typography><Typography fontWeight={700}>{data.shopName}</Typography><Typography variant="body2">{data.bannerTitle}</Typography><Chip size="small" label={data.bannerButton||'Order now'} sx={{mt:1}}/></Paper>}{module.fields.map(field=><FieldInput key={field.key} field={field} value={data[field.key]} refs={refs} onChange={v=>setData((old:any)=>({...old,[field.key]:v}))}/>)}<TextField label="Reason for change" required value={why} onChange={e=>setWhy(e.target.value)} helperText="Saved in the activity log."/>{module.key==='customers'&&record&&<><Button onClick={async()=>{try{setHistory(await api('/admin/customers/'+record.id+'/history'));}catch(e){setError((e as Error).message);}}}>View customer orders & requests</Button>{history&&<Box><Typography fontWeight={700}>Orders</Typography>{history.orders.map((o:any)=><Typography key={o.id} variant="body2">Order ID: {o.id} · {money(o.totalPaise)} · {o.status}</Typography>)}<Typography fontWeight={700} mt={2}>Medicine requests</Typography>{history.requests.map((r:any)=><Typography key={r.id} variant="body2">{r.id} · {r.followUp}</Typography>)}</Box>}</>}{record&&<Typography variant="caption" color="text.secondary">Record {record.id} · Version {record.version} · Updated {date(record.updatedAt)}</Typography>}</Stack><Divider/><Stack direction="row" spacing={1} justifyContent="flex-end" p={2}><Button onClick={onClose} disabled={busy}>Cancel</Button><Button type="submit" variant="contained" disabled={busy}>{busy?'Saving…':data.status==='published'?'Save & publish':'Save changes'}</Button></Stack></Box></Dialog>;
}
export function StockDialog({record,refs,onClose,onSaved}:{record:RecordData;refs:any;onClose:()=>void;onSaved:()=>void}){
 const [product,setProduct]=useState(record.id||''),[delta,setDelta]=useState(0),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog open onClose={onClose} fullWidth maxWidth="xs"><Box component="form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{let p=record;if(!p.id||p.id!==product){const result=await api('/admin/products?search='+encodeURIComponent(product)+'&limit=100');p=result.items.find((p:any)=>p.id===product);if(!p)throw new Error('Choose a product.');}await api('/admin/products/'+product+'/stock',{method:'POST',body:JSON.stringify({delta,reason,version:p.version})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><DialogTitle>Adjust stock</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>{error&&<Alert severity="error">{error}</Alert>}<FieldInput field={{key:'product',label:'Product',type:'select',reference:'products',required:true}} value={product} refs={refs} onChange={setProduct}/><TextField label="Change in packs" type="number" required value={delta} onChange={e=>setDelta(Number(e.target.value))} helperText="Positive to add stock. Negative to remove stock."/><TextField label="Reason" required value={reason} onChange={e=>setReason(e.target.value)}/>{record.id===product&&<Typography variant="body2">Current: {record.stock} · After adjustment: {record.stock+delta}</Typography>}</Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="contained" disabled={busy||!delta}>Save adjustment</Button></DialogActions></Box></Dialog>;
}
