import React,{useEffect,useState} from 'react';
import {Alert,Box,Button,Dialog,DialogContent,DialogTitle,DialogActions,Table,TableBody,TableCell,TableContainer,TableHead,TablePagination,TableRow,Typography} from '@mui/material';
import {api,money} from './api';
const day=(value?:string)=>value?new Date(value.slice(0,10)+'T12:00:00').toLocaleDateString('en-IN'):'Not recorded';
export default function HistoryTables({productId,revision}:{productId:string;revision:number}){
 const [data,setData]=useState<any>(),[page,setPage]=useState(0),[error,setError]=useState(''),[retry,setRetry]=useState(0),[image,setImage]=useState('');
 useEffect(()=>{let active=true;setData(undefined);setError('');api('/admin/products/'+productId+'/purchases?page='+page).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[productId,revision,page,retry]);
 return <Box>{error&&<Alert severity="error" action={<Button onClick={()=>setRetry(n=>n+1)}>Retry</Button>}>{error}</Alert>}<TableContainer><Table size="small" aria-label="Inventory purchase history"><TableHead><TableRow>{['Purchase date','Quantity','Batch number','Expiry date','Unit purchase price','Purchase total','Invoice'].map(h=><TableCell key={h} sx={{whiteSpace:'nowrap'}}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{data?.items.map((r:any)=><TableRow key={r.id}><TableCell>{day(r.purchaseDate||r.receivedDate)}<Typography variant="caption" display="block" color="text.secondary">{r.supplier}</Typography></TableCell><TableCell sx={{whiteSpace:'nowrap'}}>{r.quantity} {r.unitType||'packs'}</TableCell><TableCell>{r.batchNumber||'Not recorded'}</TableCell><TableCell>{day(r.expiryDate)}</TableCell><TableCell>{r.purchasePricePaise==null?'Not recorded':money(r.purchasePricePaise)}</TableCell><TableCell>{r.purchasePricePaise==null?'Not recorded':money(r.quantity*r.purchasePricePaise)}</TableCell><TableCell><Typography variant="caption" display="block">{r.invoice||'No invoice number'}</Typography>{r.invoiceImageId?<Button size="small" onClick={async()=>{try{const result=await api('/admin/invoices/'+r.invoiceImageId);setImage(result.uri);}catch(e){setError((e as Error).message);}}}>View invoice</Button>:<Typography variant="caption" color="text.secondary">No image attached</Typography>}</TableCell></TableRow>)}{!data?.items.length&&<TableRow><TableCell colSpan={7}>{data?'No purchases recorded yet.':error?'History could not be loaded.':'Loading purchases…'}</TableCell></TableRow>}</TableBody></Table></TableContainer>{data&&<TablePagination component="div" count={data.total} rowsPerPage={10} rowsPerPageOptions={[10]} page={page} onPageChange={(_,p)=>setPage(p)}/>}<Dialog open={!!image} onClose={()=>setImage('')} fullWidth maxWidth="md"><DialogTitle>Purchase invoice</DialogTitle><DialogContent><Box component="img" src={image} alt="Purchase invoice" sx={{width:'100%',maxHeight:'70vh',objectFit:'contain'}}/></DialogContent><DialogActions><Button onClick={()=>setImage('')}>Close</Button></DialogActions></Dialog></Box>;
}
