import React,{useEffect,useState} from 'react';
import { Tabs,Tab,Alert,Box,Button,Table,TableBody,TableCell,TableContainer,TableHead,TablePagination,TableRow,Typography } from '@mui/material';
import {api,date,money} from './api';
export default function HistoryTables({productId,revision}:{productId:string;revision:number}){
 const [tab,setTab]=useState(0);
 const [inventory,setInventory]=useState<any>(),[orders,setOrders]=useState<any>(),[page,setPage]=useState(0),[orderPage,setOrderPage]=useState(0),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setError('');Promise.all([api('/admin/inventory?productId='+encodeURIComponent(productId)+'&limit=10&page='+page),api('/admin/products/'+productId+'/purchases?page='+orderPage)]).then(([i,o])=>{if(active){setInventory(i);setOrders(o);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[productId,revision,page,orderPage,retry]);
 return <><Typography variant="h6">Inventory History</Typography><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" sx={{mb:2}}><Tab label="Supplier receipts"/><Tab label="Inventory history"/></Tabs>{error&&<Alert severity="error" action={<Button onClick={()=>setRetry(n=>n+1)}>Retry</Button>}>{error}</Alert>}{[{title:'Supplier purchases / stock receipts',data:orders,page:orderPage,setPage:setOrderPage,inventory:false},{title:'Inventory history',data:inventory,page,setPage,inventory:true}].filter((_,index)=>index===tab).map(group=><Box key={group.title}><TableContainer><Table size="small"><TableHead><TableRow>{(group.inventory?['Date','Change','Balance','Reason']:['Purchased','Batch','Expiry','Supplier','Quantity','Invoice']).map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{group.data?.items.map((row:any)=><TableRow key={row.id}>{(group.inventory?[date(row.createdAt),(row.delta>0?'+':'')+row.delta,row.balance+' packs',row.reason]:[date(row.receivedDate),row.batchNumber||'Not recorded',row.expiryDate||'Not recorded',row.supplier,row.quantity+' '+(row.unitType||'packs'),row.invoice||'—']).map((v:any,i:number)=><TableCell key={i}>{v}</TableCell>)}</TableRow>)}{!group.data?.items.length&&<TableRow><TableCell colSpan={6}>{group.data?'No history recorded.':'Loading history…'}</TableCell></TableRow>}</TableBody></Table></TableContainer>{group.data&&<TablePagination component="div" count={group.data.total} rowsPerPage={10} rowsPerPageOptions={[10]} page={group.page} onPageChange={(_,p)=>group.setPage(p)}/>}</Box>)}</>;
}
