import React,{useEffect,useState} from 'react';
import {Accordion,AccordionSummary,AccordionDetails,Alert,Autocomplete,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,Stack,Tab,Tabs,TextField,Typography} from '@mui/material';
import Close from '@mui/icons-material/Close';
import ExpandMore from '@mui/icons-material/ExpandMore';
import HistoryTables from './HistoryTables';
import {MedicationOutlined,Inventory2Outlined,ReceiptLongOutlined,PaymentsOutlined,HealthAndSafetyOutlined} from '@mui/icons-material';
import MedicinePhoto from './MedicinePhoto';
import {inventoryFields,modules,type RecordData} from '@pharmacy/domain/admin';
import {FieldInput} from './Editor';
import {api,money,date} from './api';
const defaults=()=>({image:'',...Object.fromEntries(inventoryFields.filter(f=>f.key!=='quantityAvailable').map(f=>[f.key,f.type==='boolean'?false:f.type==='number'||f.type==='money'?0:'']))});
const sections=[{label:'Medicine',icon:<MedicationOutlined/>,keys:['brandName','genericName','strength','dosageForm','manufacturer','category','packageSize']},{label:'Inventory',icon:<Inventory2Outlined/>,keys:['unitType','quantityReceived','quantityAvailable','batchNumber','manufacturingDate','expiryDate','supplier','invoice','purchaseDate','purchasePricePaise']},{label:'Pricing',icon:<PaymentsOutlined/>,keys:['mrpPaise','pricePaise','hsnCode','gstRate']},{label:'Other',icon:<HealthAndSafetyOutlined/>,keys:['prescriptionRequired','drugSchedule','barcode','storageRequirement']}];
const sectionFor=(key:string)=>Math.max(0,sections.findIndex(s=>s.keys.includes(key)));
export function InventoryForm({product,refs,onClose,onSaved}:{product?:RecordData;refs:any;onClose:()=>void;onSaved:()=>void}){
 const [tab,setTab]=useState(0),[uploading,setUploading]=useState(false),[receiptMode,setReceiptMode]=useState(!product),[latest,setLatest]=useState<any>(),[historyRevision]=useState(0),[publication,setPublication]=useState(product?.status||'draft');
 const [selected,setSelected]=useState(product),[data,setData]=useState<any>(()=>({...defaults(),...Object.fromEntries(inventoryFields.filter(f=>product?.[f.key]!==undefined&&['brandName','genericName','strength','dosageForm','category','packageSize','prescriptionRequired'].includes(f.key)).map(f=>[f.key,product![f.key]])),manufacturer:product?.manufacturerGroup||'',image:product?.image||'',mrpPaise:product?.mrpPaise||0,pricePaise:product?.pricePaise||0})),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!product)return;let alive=true;api('/admin/batches?productId='+product.id+'&limit=1').then(r=>{if(alive&&r.items[0]){setLatest(r.items[0]);setData((d:any)=>({...d,...Object.fromEntries(inventoryFields.filter(f=>f.key!=='quantityAvailable'&&!['brandName','genericName','strength','dosageForm','manufacturer','category','packageSize','prescriptionRequired'].includes(f.key)).map(f=>[f.key,r.items[0][f.key]??d[f.key]]))}));}}).catch(e=>setError(e.message));return()=>{alive=false;};},[product?.id]);
 const identity=['brandName','genericName','strength','dosageForm','manufacturer','category','packageSize','prescriptionRequired'];
 async function select(id?:string){setError('');if(!id){setSelected(undefined);setData(defaults());return;}setBusy(true);try{const result=await api('/admin/products?search='+encodeURIComponent(id)+'&limit=100');const p=result.items.find((r:any)=>r.id===id);if(!p)throw new Error('Medicine not found.');setSelected(p);setData({...defaults(),image:p.image||'',...Object.fromEntries(identity.map(k=>[k,k==='manufacturer'?p.manufacturerGroup:p[k]??'']))});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog open fullWidth maxWidth="md" onClose={busy||uploading?undefined:onClose}><Box component="form" noValidate sx={{display:'flex',flexDirection:'column',maxHeight:'90vh'}} onSubmit={async e=>{e.preventDefault();if(busy||uploading)return;if(selected&&!receiptMode){if(!data.image||reason.trim().length<3){setError('Add a photograph and a change note of at least 3 characters.');return;}setBusy(true);setError('');try{const module=modules.find(m=>m.key==='products')!;const payload={...Object.fromEntries(module.fields.filter(f=>selected[f.key]!==undefined).map(f=>[f.key,selected[f.key]])),...Object.fromEntries(identity.filter(k=>k!=='manufacturer').map(k=>[k,data[k]])),status:publication,manufacturer:data.manufacturer,manufacturerGroup:data.manufacturer,image:data.image,imageAlt:data.brandName};await api('/admin/products/'+selected.id,{method:'PUT',body:JSON.stringify({data:payload,version:selected.version,reason})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}return;}const missing=inventoryFields.find(f=>f.required&&((f.type!=='money'&&f.type!=='number'&&!data[f.key])||(['quantityReceived','mrpPaise'].includes(f.key)&&data[f.key]<=0)));if(!data.image||missing||reason.trim().length<3){setTab(!data.image?0:missing?sectionFor(missing.key):3);setError(!data.image?'Add a medicine photograph.':missing?'Please enter '+missing.label+'.':'Add a receipt note of at least 3 characters.');return;}setBusy(true);setError('');try{await api('/admin/inventory/receive',{method:'POST',body:JSON.stringify({productId:selected?.id,version:selected?.version,data,reason})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <DialogTitle><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="overline" color="primary">{selected?'Product details':'New product'}</Typography><Typography variant="h5">{selected?selected.brandName:'Add Product'}</Typography></Box><IconButton aria-label="Close inventory" disabled={busy||uploading} onClick={onClose}><Close/></IconButton></Stack></DialogTitle>
 <Tabs value={tab} onChange={(_,v)=>{if(!busy&&!uploading)setTab(v);}} variant="scrollable" scrollButtons="auto">{sections.map(s=><Tab key={s.label} label={s.label} icon={s.icon} iconPosition="start"/>)}</Tabs>
 <DialogContent dividers><Stack spacing={2}>{error&&<Alert severity="error">{error}</Alert>}{tab===0&&!product&&<Autocomplete disabled={busy||uploading} options={refs.products||[]} value={(refs.products||[]).find((p:any)=>p.id===selected?.id)||null} getOptionLabel={(p:any)=>p.name} isOptionEqualToValue={(a:any,b:any)=>a.id===b.id} onChange={(_,p:any)=>void select(p?.id)} renderInput={params=><TextField {...params} label="Existing medicine (leave empty for a new medicine)"/>}/>}
 {receiptMode&&selected&&!selected.batchManaged&&selected.stock>0&&<Alert severity="warning">{selected.stock} packs have no batch details. On the first receipt, these will be held out of available stock until reconciled. Enter only verified quantities; do not count the same stock twice.</Alert>}
 {tab===0&&<MedicinePhoto value={data.image} disabled={busy} onBusy={setUploading} onChange={image=>setData((d:any)=>({...d,image}))}/>}{tab===1&&<Typography variant="body2" color="text.secondary">Purchase prices are visible only to your pharmacy team.</Typography>}
 {selected&&!receiptMode&&tab===1&&<Stack direction="row" alignItems="center" justifyContent="space-between"><Typography variant="body2">{latest?'Latest batch (read-only)':'No batch receipts yet'}</Typography><Button variant="outlined" onClick={()=>{setReceiptMode(true);setData((d:any)=>({...d,...Object.fromEntries(inventoryFields.filter(f=>f.key!=='quantityAvailable'&&!identity.includes(f.key)).map(f=>[f.key,f.type==='number'||f.type==='money'?0:'']))}));}}>Receive stock</Button></Stack>}<Box className="detail-fields">{inventoryFields.filter(f=>sections[tab].keys.includes(f.key)).map((field,index)=><React.Fragment key={field.key}><Box component="fieldset" disabled={busy||!!selected&&(receiptMode?identity.includes(field.key):!identity.includes(field.key))} sx={{border:0,m:0,p:0,minWidth:0}}>{field.key==='quantityAvailable'?<TextField fullWidth label={field.label} value={receiptMode?data.quantityReceived||0:latest?.quantityAvailable??selected?.stock??0} slotProps={{input:{readOnly:true}}} helperText="Calculated from receipts and batch movements."/>:<FieldInput field={field.key==='gstRate'?{...field,help:'Percentage from 0 to 100'}:field} value={data[field.key]} refs={refs} onChange={value=>setData((d:any)=>({...d,[field.key]:value}))}/>}</Box></React.Fragment>)}</Box>
 {selected&&!receiptMode&&tab===0&&<FieldInput field={modules.find(m=>m.key==='products')!.fields.find(f=>f.key==='status')!} value={publication} refs={refs} onChange={setPublication}/>}<Box hidden={tab!==3}><TextField fullWidth required label={receiptMode?'Receipt note':'Change note'} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></Box>{selected&&<Accordion disableGutters elevation={0}><AccordionSummary expandIcon={<ExpandMore/>}><Typography fontWeight={700}>Inventory History</Typography></AccordionSummary><AccordionDetails><HistoryTables productId={selected.id} revision={historyRevision}/></AccordionDetails></Accordion>}</Stack></DialogContent><DialogActions><Button disabled={busy||uploading} onClick={onClose}>Cancel</Button><Box flex={1}/>{tab>0&&<Button disabled={busy||uploading} onClick={()=>setTab(t=>t-1)}>Back</Button>}{tab<3?<Button variant="contained" disabled={busy||uploading} onClick={()=>setTab(t=>t+1)}>Next</Button>:<Button type="submit" variant="contained" disabled={busy||uploading}>{busy?'Saving…':selected&&!receiptMode?'Save changes':'Save product & stock'}</Button>}</DialogActions></Box></Dialog>;
}
export function BatchDetails({record,role,onClose,onSaved}:{record:RecordData;role:string;onClose:()=>void;onSaved:()=>void}){
 const [tab,setTab]=useState(0);
 const [history,setHistory]=useState<any[]>([]);
 useEffect(()=>{api('/admin/inventory?batchId='+record.id+'&limit=100').then(r=>setHistory(r.items)).catch(e=>setError(e.message));},[record.id]);
 const [kind,setKind]=useState('adjustment'),[delta,setDelta]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog open fullWidth maxWidth="md" onClose={busy?undefined:onClose}><DialogTitle><Stack direction="row" justifyContent="space-between"><Box><Typography variant="overline" color="primary">Batch {record.batchNumber}</Typography><Typography variant="h5">{record.brandName}</Typography></Box><IconButton aria-label="Close batch" onClick={onClose}><Close/></IconButton></Stack></DialogTitle><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto">{sections.map(s=><Tab key={s.label} label={s.label} icon={s.icon} iconPosition="start"/>)}<Tab label="Activity"/></Tabs><DialogContent dividers>{record.expiryDate<new Date().toISOString().slice(0,10)&&<Alert severity="warning" sx={{mb:2}}>Expired batch — {record.quantityOnHand??record.quantityAvailable} packs remain on hand, excluded from available stock. Record an expiry movement when removed.</Alert>}<Box className="detail-metrics">{[['Received',record.quantityReceived],['Available',record.quantityAvailable],['Expiry',record.expiryDate]].map(([k,v])=><Box className="detail-metric" key={k}><Typography variant="caption">{k}</Typography><Typography variant="h6">{v}</Typography></Box>)}</Box>{tab===0&&record.image&&<Box component="img" src={record.image} alt={record.brandName+' pack'} sx={{height:140,width:'100%',objectFit:'contain',mb:2}}/>}<Box className="detail-section detail-fields" hidden={tab===4}>{inventoryFields.filter(f=>sections[tab]?.keys.includes(f.key)).map(f=><Box key={f.key}><Typography variant="caption" color="text.secondary">{f.label}</Typography><Typography fontWeight={600} sx={{overflowWrap:'anywhere'}}>{f.type==='money'?money(record[f.key]||0):f.type==='boolean'?record[f.key]?'Yes':'No':record[f.key]||'—'}</Typography></Box>)}</Box><Typography variant="body2" color="text.secondary" my={2}>Receipt details are a permanent snapshot. Receive a new batch for a new purchase; use a reasoned movement to correct stock.</Typography>
 <Box hidden={tab!==4}><Box className="detail-section" sx={{mb:2}}><Typography variant="h6">Batch movement history</Typography>{history.map(h=><Stack key={h.id} direction="row" justifyContent="space-between" gap={2} sx={{py:1,borderBottom:1,borderColor:'divider'}}><Box><Typography variant="body2">{h.reason}</Typography><Typography variant="caption" color="text.secondary">{date(h.createdAt)}</Typography></Box><Typography fontWeight={700}>{h.delta>0?'+':''}{h.delta} · {h.balance} remaining</Typography></Stack>)}</Box>{role==='admin'&&<Box component="form" className="detail-section" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/admin/batches/'+record.id+'/movements',{method:'POST',body:JSON.stringify({kind,delta:Number(delta),reason,version:record.version})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Typography variant="h6">Record stock movement</Typography>{error&&<Alert severity="error">{error}</Alert>}<Stack gap={2}><FieldInput field={{key:'kind',label:'Movement',type:'select',choices:['return','damage','expiry','adjustment']}} value={kind} refs={{}} onChange={setKind}/><TextField required label="Quantity change" type="number" value={delta} onChange={e=>setDelta(e.target.value)} helperText="Use a negative quantity to remove stock, positive to add." slotProps={{htmlInput:{step:1}}}/><TextField required label="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><Button type="submit" variant="contained" disabled={busy||!Number(delta)}>Save movement</Button></Stack></Box>}
 </Box></DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>;
}
