import React,{useEffect,useState} from 'react';
import {Alert,Autocomplete,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,Stack,TextField,Typography} from '@mui/material';
import Close from '@mui/icons-material/Close';
import {inventoryFields,type RecordData} from '@pharmacy/domain/admin';
import {FieldInput} from './Editor';
import {api,money,date} from './api';
const defaults=()=>Object.fromEntries(inventoryFields.filter(f=>f.key!=='quantityAvailable').map(f=>[f.key,f.type==='boolean'?false:f.type==='number'||f.type==='money'?0:'']));
export function InventoryForm({product,refs,onClose,onSaved}:{product?:RecordData;refs:any;onClose:()=>void;onSaved:()=>void}){
 const [selected,setSelected]=useState(product),[data,setData]=useState<any>(()=>({...defaults(),...Object.fromEntries(inventoryFields.filter(f=>product?.[f.key]!==undefined&&['brandName','genericName','strength','dosageForm','category','packageSize','prescriptionRequired'].includes(f.key)).map(f=>[f.key,product![f.key]])),manufacturer:product?.manufacturerGroup||''})),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const identity=['brandName','genericName','strength','dosageForm','manufacturer','category','packageSize','prescriptionRequired'];
 async function select(id?:string){setError('');if(!id){setSelected(undefined);setData(defaults());return;}setBusy(true);try{const result=await api('/admin/products?search='+encodeURIComponent(id)+'&limit=100');const p=result.items.find((r:any)=>r.id===id);if(!p)throw new Error('Medicine not found.');setSelected(p);setData({...defaults(),...Object.fromEntries(identity.map(k=>[k,k==='manufacturer'?p.manufacturerGroup:p[k]??'']))});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog open fullWidth maxWidth="md" onClose={busy?undefined:onClose}><Box component="form" sx={{display:'flex',flexDirection:'column',maxHeight:'90vh'}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/admin/inventory/receive',{method:'POST',body:JSON.stringify({productId:selected?.id,version:selected?.version,data,reason})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <DialogTitle><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="overline" color="primary">Batch receipt</Typography><Typography variant="h5">Medicine Inventory</Typography></Box><IconButton aria-label="Close inventory" disabled={busy} onClick={onClose}><Close/></IconButton></Stack></DialogTitle>
 <DialogContent dividers><Stack spacing={2}>{error&&<Alert severity="error">{error}</Alert>}{!product&&<Autocomplete disabled={busy} options={refs.products||[]} value={(refs.products||[]).find((p:any)=>p.id===selected?.id)||null} getOptionLabel={(p:any)=>p.name} isOptionEqualToValue={(a:any,b:any)=>a.id===b.id} onChange={(_,p:any)=>void select(p?.id)} renderInput={params=><TextField {...params} label="Existing medicine (leave empty for a new medicine)"/>}/>}
 {selected&&!selected.batchManaged&&selected.stock>0&&<Alert severity="warning">{selected.stock} packs have no batch details. On the first receipt, these will be held out of available stock until reconciled. Enter only verified quantities; do not count the same stock twice.</Alert>}
 <Typography variant="body2" color="text.secondary">Dropdowns come from Master Data. Purchase prices remain private. Existing medicine details are read-only in a receipt.</Typography>
 <Box className="detail-fields">{inventoryFields.map((field,index)=><React.Fragment key={field.key}>{field.group&&<Typography variant="h6" color="primary" sx={{gridColumn:'1 / -1',mt:index?2:0,borderBottom:1,borderColor:'divider',pb:1}}>{field.group}</Typography>}<Box component="fieldset" disabled={busy||!!selected&&identity.includes(field.key)} sx={{border:0,m:0,p:0,minWidth:0}}>{field.key==='quantityAvailable'?<TextField fullWidth label={field.label} value={data.quantityReceived||0} slotProps={{input:{readOnly:true}}} helperText="Calculated from receipts and batch movements."/>:<FieldInput field={field.key==='gstRate'?{...field,help:'Percentage from 0 to 100'}:field} value={data[field.key]} refs={refs} onChange={value=>setData((d:any)=>({...d,[field.key]:value}))}/>}</Box></React.Fragment>)}</Box>
 <TextField required label="Reason / receipt note" value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></Stack></DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" variant="contained" disabled={busy}>{busy?'Saving…':'Save batch receipt'}</Button></DialogActions></Box></Dialog>;
}
export function BatchDetails({record,role,onClose,onSaved}:{record:RecordData;role:string;onClose:()=>void;onSaved:()=>void}){
 const [history,setHistory]=useState<any[]>([]);
 useEffect(()=>{api('/admin/inventory?batchId='+record.id+'&limit=100').then(r=>setHistory(r.items)).catch(e=>setError(e.message));},[record.id]);
 const [kind,setKind]=useState('adjustment'),[delta,setDelta]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog open fullWidth maxWidth="md" onClose={busy?undefined:onClose}><DialogTitle><Stack direction="row" justifyContent="space-between"><Box><Typography variant="overline" color="primary">Batch {record.batchNumber}</Typography><Typography variant="h5">{record.brandName}</Typography></Box><IconButton aria-label="Close batch" onClick={onClose}><Close/></IconButton></Stack></DialogTitle><DialogContent dividers>{record.expiryDate<new Date().toISOString().slice(0,10)&&<Alert severity="warning" sx={{mb:2}}>Expired batch — {record.quantityOnHand??record.quantityAvailable} packs remain on hand, excluded from available stock. Record an expiry movement when removed.</Alert>}<Box className="detail-metrics">{[['Received',record.quantityReceived],['Available',record.quantityAvailable],['Expiry',record.expiryDate]].map(([k,v])=><Box className="detail-metric" key={k}><Typography variant="caption">{k}</Typography><Typography variant="h6">{v}</Typography></Box>)}</Box><Box className="detail-section detail-fields">{inventoryFields.filter(f=>!['quantityReceived','quantityAvailable','expiryDate'].includes(f.key)).map(f=><Box key={f.key}><Typography variant="caption" color="text.secondary">{f.label}</Typography><Typography fontWeight={600} sx={{overflowWrap:'anywhere'}}>{f.type==='money'?money(record[f.key]||0):f.type==='boolean'?record[f.key]?'Yes':'No':record[f.key]||'—'}</Typography></Box>)}</Box><Typography variant="body2" color="text.secondary" my={2}>Receipt details are a permanent snapshot. Receive a new batch for a new purchase; use a reasoned movement to correct stock.</Typography>
 <Box className="detail-section" sx={{mb:2}}><Typography variant="h6">Batch movement history</Typography>{history.map(h=><Stack key={h.id} direction="row" justifyContent="space-between" gap={2} sx={{py:1,borderBottom:1,borderColor:'divider'}}><Box><Typography variant="body2">{h.reason}</Typography><Typography variant="caption" color="text.secondary">{date(h.createdAt)}</Typography></Box><Typography fontWeight={700}>{h.delta>0?'+':''}{h.delta} · {h.balance} remaining</Typography></Stack>)}</Box>{role==='admin'&&<Box component="form" className="detail-section" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/admin/batches/'+record.id+'/movements',{method:'POST',body:JSON.stringify({kind,delta:Number(delta),reason,version:record.version})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Typography variant="h6">Record stock movement</Typography>{error&&<Alert severity="error">{error}</Alert>}<Stack gap={2}><FieldInput field={{key:'kind',label:'Movement',type:'select',choices:['return','damage','expiry','adjustment']}} value={kind} refs={{}} onChange={setKind}/><TextField required label="Quantity change" type="number" value={delta} onChange={e=>setDelta(e.target.value)} helperText="Use a negative quantity to remove stock, positive to add." slotProps={{htmlInput:{step:1}}}/><TextField required label="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><Button type="submit" variant="contained" disabled={busy||!Number(delta)}>Save movement</Button></Stack></Box>}
 </DialogContent><DialogActions><Button onClick={onClose}>Close</Button></DialogActions></Dialog>;
}
