import React,{useEffect,useRef,useState} from 'react';
import {Alert,Box,Button,Stack,Typography} from '@mui/material';
import {AddPhotoAlternateOutlined} from '@mui/icons-material';
import {api} from './api';
export default function MedicinePhoto({value,onChange,disabled=false,onBusy}:{value:string;onChange:(url:string)=>void;disabled?:boolean;onBusy?:(busy:boolean)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 return <Box sx={{p:2,border:'1px dashed',borderColor:'divider',borderRadius:3,bgcolor:'white'}}><Stack direction={{xs:'column',sm:'row'}} spacing={2} alignItems="center"><Box sx={{width:100,height:110,bgcolor:'#f1f6f3',borderRadius:2,display:'grid',placeItems:'center',overflow:'hidden',flexShrink:0}}>{value?<Box component="img" src={value} alt="Medicine pack" sx={{width:'100%',height:'100%',objectFit:'contain'}}/>:<AddPhotoAlternateOutlined sx={{fontSize:38,color:'primary.main'}}/>}</Box><Box sx={{minWidth:0,textAlign:{xs:'center',sm:'left'}}}><Typography fontWeight={700}>Medicine photograph</Typography><Typography variant="body2" color="text.secondary">A clear picture of the pack.</Typography><Button component="label" disabled={disabled||busy} startIcon={<AddPhotoAlternateOutlined/>}>{busy?'Uploading…':value?'Change photograph':'Upload photograph'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);onBusy?.(true);setError('');try{const form=new FormData();form.append('file',file);const result=await api('/media?public=true',{method:'POST',body:form});if(alive.current)onChange(result.uri);}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current){setBusy(false);onBusy?.(false);}}}}/></Button></Box></Stack>{error&&<Alert severity="error">{error}</Alert>}</Box>;
}
