import React,{useEffect,useState} from 'react';
import {Accordion,AccordionSummary,AccordionDetails,Alert,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,Divider,IconButton,Stack,TextField,Typography} from '@mui/material';
import ExpandMore from '@mui/icons-material/ExpandMore';
import Close from '@mui/icons-material/Close';
import {modules,type Field,type RecordData} from '@pharmacy/domain/admin';
import {api} from './api';
import {InlineField} from './InlineField';
import HistoryTables from './HistoryTables';
const productModule=modules.find(m=>m.key==='products')!;
const pick=(key:string,row:any)=>Object.fromEntries(modules.find(m=>m.key===key)!.fields.filter(f=>row[f.key]!==undefined).map(f=>[f.key,row[f.key]]));
const emptyReceipt=()=>({supplier:'',quantity:0,receivedDate:new Date().toISOString().slice(0,10),invoice:''});
export default function ProductDetail({record,refs,onClose,onUpdated}:{record:RecordData;refs:any;onClose:()=>void;onUpdated:(message:string)=>void}){
 const [current,setCurrent]=useState(record),[draft,setDraft]=useState<any>(pick('products',record)),[related,setRelated]=useState<Record<string,RecordData>>({}),[relatedDraft,setRelatedDraft]=useState<Record<string,any>>({}),[active,setActive]=useState<string[]>([]),[stock,setStock]=useState(record.stock),[receipt,setReceipt]=useState(emptyReceipt),[why,setWhy]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let alive=true;Promise.all([api('/admin/manufacturers?limit=100'),api('/admin/categories?limit=100')]).then(([m,c])=>{if(alive){const rows=[...m.items.map((r:any)=>['manufacturers:'+r.id,r]),...c.items.map((r:any)=>['categories:'+r.id,r])];setRelated(Object.fromEntries(rows));setRelatedDraft(Object.fromEntries(rows.map(([key,r])=>[key,pick(key.split(':')[0],r)])));}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[revision]);
 const manufacturer=Object.entries(related).find(([key,r])=>key.startsWith('manufacturers:')&&r.name===draft.manufacturerGroup);
 const category=Object.entries(related).find(([key,r])=>key.startsWith('categories:')&&r.subcategories.includes(draft.category));
 const activate=(key:string)=>setActive(old=>old.includes(key)?old:[...old,key]);
 const cancel=()=>{setDraft(pick('products',current));setStock(current.stock);setRelatedDraft(Object.fromEntries(Object.entries(related).map(([key,r])=>[key,pick(key.split(':')[0],r)])));setReceipt(emptyReceipt());setActive([]);setWhy('');setError('');};
 const changed=JSON.stringify(draft)!==JSON.stringify(pick('products',current))||stock!==current.stock||receipt.quantity!==0||receipt.supplier!==''||receipt.invoice!==''||Object.entries(relatedDraft).some(([key,value])=>JSON.stringify(value)!==JSON.stringify(pick(key.split(':')[0],related[key])));
 const render=(field:Field,scope='product')=>{const key=scope+':'+field.key;const value=scope==='product'?draft[field.key]:scope==='stock'?stock:scope==='receipt'?(receipt as any)[field.key]:relatedDraft[scope]?.[field.key];return <InlineField key={key} field={field} value={value} refs={refs} editing={active.includes(key)} disabled={busy} onEdit={()=>activate(key)} onChange={v=>{if(scope==='product')setDraft((d:any)=>({...d,[field.key]:v}));else if(scope==='stock')setStock(v);else if(scope==='receipt')setReceipt(r=>({...r,[field.key]:v}));else setRelatedDraft(d=>({...d,[scope]:{...d[scope],[field.key]:v}}));}}/>;};
 const grid={display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:1};
 return <Dialog open fullWidth maxWidth="md" onClose={busy?undefined:()=>{cancel();onClose();}} aria-label="Product details"><Box component="form" onSubmit={async e=>{e.preventDefault();if(!changed)return;setBusy(true);setError('');try{
  const changes:any[]=[];if(JSON.stringify(draft)!==JSON.stringify(pick('products',current)))changes.push({collection:'products',id:current.id,version:current.version,data:draft});
  for(const [key,data]of Object.entries(relatedDraft)){const row=related[key],collection=key.split(':')[0];if(JSON.stringify(data)!==JSON.stringify(pick(collection,row)))changes.push({collection,id:row.id,version:row.version,data});}
  const result=await api('/admin/products/'+current.id+'/details',{method:'PUT',body:JSON.stringify({version:current.version,reason:why,changes,...(stock!==current.stock?{stock}:{}),...(receipt.quantity||receipt.supplier||receipt.invoice?{receipt}:{})})});
  setCurrent(result);setDraft(pick('products',result));setStock(result.stock);setReceipt(emptyReceipt());setActive([]);setWhy('');setRevision(n=>n+1);onUpdated('Product changes saved successfully.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}} sx={{display:'flex',flexDirection:'column',maxHeight:'88vh'}}>
 <DialogTitle component="div"><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h5">{current.brandName}</Typography><IconButton aria-label="Close product details" disabled={busy} onClick={()=>{cancel();onClose();}}><Close/></IconButton></Stack><Typography variant="body2" color="text.secondary">Product overview · Double-click a field to edit, then save your changes.</Typography></DialogTitle>
 <DialogContent dividers><Stack spacing={2.5}>{error&&<Alert severity="error">{error}</Alert>}
 <Box className="detail-section"><Typography variant="overline" color="primary">Manufacturer</Typography><Box sx={grid}>{productModule.fields.filter(f=>['manufacturerGroup','manufacturer'].includes(f.key)).map(f=>render(f))}{manufacturer&&['legalName','website'].map(key=>render({...modules.find(m=>m.key==='manufacturers')!.fields.find(f=>f.key===key)!,label:key==='legalName'?'Registered manufacturer name':'Manufacturer website'},manufacturer[0]))}</Box>{manufacturer&&<Typography variant="caption" color="text.secondary">Registered name and website are shared by products in this manufacturer group.</Typography>}</Box>
 <Box className="detail-section"><Typography variant="h6">Medicine details</Typography><Box sx={grid}>{productModule.fields.filter(f=>!['manufacturerGroup','manufacturer','imageAlt','imageRights','sourceUrl','sourceCheckedAt'].includes(f.key)).map(f=>render(f))}{category&&render({...modules.find(m=>m.key==='categories')!.fields.find(f=>f.key==='name')!,label:'Broad category'},category[0])}</Box></Box>
 <Accordion disableGutters elevation={0}><AccordionSummary expandIcon={<ExpandMore/>}><Typography fontWeight={600}>Image credits & verification</Typography></AccordionSummary><AccordionDetails><Box sx={grid}>{productModule.fields.filter(f=>['imageAlt','imageRights','sourceUrl','sourceCheckedAt'].includes(f.key)).map(f=>render(f))}</Box></AccordionDetails></Accordion>
 <Box className="detail-section"><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="overline" color="primary">Inventory</Typography><Typography variant="body2" color="text.secondary">Available packs</Typography></Box><Box sx={{minWidth:150}}>{render({key:'stock',label:'Current stock',type:'number',required:true},'stock')}</Box></Stack>
 <Accordion disableGutters elevation={0} sx={{mt:2}}><AccordionSummary expandIcon={<ExpandMore/>}><Typography fontWeight={600}>Receive stock from a supplier</Typography></AccordionSummary><AccordionDetails><Typography variant="body2" color="text.secondary" mb={2}>Double-click to enter a receipt. Stock updates when you save.</Typography><Box sx={grid}>{([{key:'supplier',label:'Supplier',required:true},{key:'quantity',label:'Quantity (packs)',type:'number',required:true},{key:'receivedDate',label:'Received date',type:'date',required:true},{key:'invoice',label:'Invoice reference'}] as Field[]).map(f=>render(f,'receipt'))}</Box></AccordionDetails></Accordion></Box>
 <Box className="detail-section"><HistoryTables productId={current.id} revision={revision}/></Box>
 </Stack></DialogContent><DialogActions sx={{p:2,alignItems:'center',gap:1,flexWrap:'wrap'}}>{active.length>0&&<TextField label="Reason for change" required value={why} onChange={e=>setWhy(e.target.value)} disabled={busy} sx={{flex:1,minWidth:200}}/>}<Button disabled={busy} onClick={cancel}>Cancel</Button><Button type="submit" variant="contained" disabled={busy||!changed}>{busy?'Saving…':'Save changes'}</Button></DialogActions></Box></Dialog>;
}
