import React,{useState} from 'react';
import {Alert,Avatar,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,Stack,Tab,Tabs,TextField,Typography} from '@mui/material';
import {Close,MedicationOutlined,Inventory2Outlined,HistoryOutlined} from '@mui/icons-material';
import {modules,inventoryFields,type Field,type RecordData} from '@pharmacy/domain/admin';
import {api} from './api';
import {InlineField} from './InlineField';
import HistoryTables from './HistoryTables';
import {InventoryForm} from './InventoryForm';
import MedicinePhoto from './MedicinePhoto';
const module=modules.find(m=>m.key==='products')!;
const pick=(row:RecordData)=>Object.fromEntries(module.fields.filter(f=>row[f.key]!==undefined).map(f=>[f.key,row[f.key]]));
export default function ProductDetail({record,refs,onClose,onUpdated}:{record:RecordData;refs:any;onClose:()=>void;onUpdated:(message:string)=>void}){
 const [current,setCurrent]=useState(record),[draft,setDraft]=useState<any>(pick(record)),[tab,setTab]=useState(0),[active,setActive]=useState<string[]>([]),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[receiving,setReceiving]=useState(false);
 const dirty=JSON.stringify(draft)!==JSON.stringify(pick(current));
 const cancel=()=>{setDraft(pick(current));setActive([]);setReason('');setError('');};
 const render=(field:Field)=>{const key=field.key==='manufacturer'?'manufacturerGroup':field.key;return <InlineField key={key} field={{...field,key}} value={draft[key]} refs={refs} editing={active.includes(key)} disabled={busy||uploading} onEdit={()=>setActive(a=>[...a,key])} onChange={v=>setDraft((d:any)=>({...d,[key]:v,...(key==='manufacturerGroup'?{manufacturer:v}:{})}))}/>;};
 if(receiving)return <InventoryForm product={current} refs={refs} onClose={()=>setReceiving(false)} onSaved={()=>{onUpdated('Batch receipt saved successfully.');onClose();}}/>;
 return <Dialog open fullWidth maxWidth="md" onClose={busy||uploading?undefined:onClose} aria-label="Product details"><Box component="form" noValidate onSubmit={async e=>{e.preventDefault();if(busy||uploading)return;const data={...draft,composition:draft.composition||draft.genericName,imageAlt:draft.brandName};const missing=module.fields.find(f=>f.required&&!data[f.key]&&f.type!=='money');if(missing||reason.trim().length<3){setTab(missing&&['mrpPaise','pricePaise'].includes(missing.key)?1:0);setError(missing?'Please enter '+(missing.key==='manufacturerGroup'?'Manufacturer':missing.label)+'.':'Add a reason of at least 3 characters.');return;}setBusy(true);setError('');try{const saved=await api('/admin/products/'+current.id+'/details',{method:'PUT',body:JSON.stringify({version:current.version,reason,changes:[{collection:'products',id:current.id,version:current.version,data}]})});setCurrent(saved);setDraft(pick(saved));setActive([]);setReason('');onUpdated('Medicine details saved successfully.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}} sx={{display:'flex',flexDirection:'column',maxHeight:'90vh'}}>
 <DialogTitle component="div"><Stack direction="row" spacing={2} alignItems="center"><Avatar variant="rounded" src={draft.image} sx={{width:52,height:60,bgcolor:'white'}}><MedicationOutlined/></Avatar><Box flex={1}><Typography variant="overline" color="primary">Medicine</Typography><Typography variant="h5">{current.brandName}</Typography></Box><IconButton aria-label="Close product details" disabled={busy||uploading} onClick={onClose}><Close/></IconButton></Stack></DialogTitle>
 <Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto"><Tab icon={<MedicationOutlined/>} iconPosition="start" label="Medicine"/><Tab icon={<Inventory2Outlined/>} iconPosition="start" label="Stock & pricing"/><Tab icon={<HistoryOutlined/>} iconPosition="start" label="History"/></Tabs>
 <DialogContent dividers>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Box hidden={tab!==0}><Stack spacing={2}><MedicinePhoto value={draft.image||''} disabled={busy} onBusy={setUploading} onChange={image=>setDraft((d:any)=>({...d,image}))}/><Typography variant="body2" color="text.secondary">Double-click a detail to edit. Save applies your changes.</Typography><Box className="detail-section detail-fields">{inventoryFields.slice(0,7).map(render)}{render(inventoryFields.find(f=>f.key==='prescriptionRequired')!)}{render(module.fields.find(f=>f.key==='status')!)}</Box></Stack></Box>
 <Box hidden={tab!==1}><Stack spacing={2}><Box className="detail-section"><Stack direction="row" justifyContent="space-between" alignItems="center" gap={2}><Box><Typography variant="overline">Available stock</Typography><Typography variant="h4">{current.stock} <Typography component="span">packs</Typography></Typography></Box><Button variant="contained" disabled={dirty||busy||uploading} onClick={()=>setReceiving(true)}>Receive batch</Button></Stack><Typography variant="body2" color="text.secondary" mt={2}>{current.batchManaged?'Batch prices and stock are managed in Medicine Inventory.':'Add verified batches to reconcile this opening stock.'}</Typography></Box>{!current.batchManaged&&<Box className="detail-section detail-fields">{inventoryFields.filter(f=>['mrpPaise','pricePaise'].includes(f.key)).map(render)}</Box>}</Stack></Box>
 <Box hidden={tab!==2}><HistoryTables productId={current.id} revision={current.version}/></Box></DialogContent>
 <DialogActions sx={{gap:1,flexWrap:'wrap'}}>{(dirty||active.length>0)&&<TextField required label="Reason for change" value={reason} onChange={e=>setReason(e.target.value)} disabled={busy||uploading} sx={{flex:1,minWidth:180}}/>}<Button disabled={busy||uploading} onClick={cancel}>Cancel</Button><Button type="submit" variant="contained" disabled={!dirty||busy||uploading}>{busy?'Saving…':'Save changes'}</Button></DialogActions></Box></Dialog>;
}
