import { Medicine } from "./index";

// Pack and Rx references checked 20 September 2026. Selling prices and MRPs are illustrative testing values, not verified retail prices or live stock.
export const indianMedicines: Medicine[] = [
  {
    "id": "abbott-digene-mint",
    "brandName": "Digene Mint",
    "genericName": "Antacid combination",
    "strength": "Mint",
    "dosageForm": "Chewable tablet",
    "packageSize": "15 tablets",
    "category": "Digestive care",
    "price": 28,
    "mrp": 33.6,
    "manufacturer": "Abbott India Ltd",
    "manufacturerGroup": "Abbott",
    "composition": "ALUMINIUM HYDROXIDE-300MG+MAGNESIUM ALUMINIUM SILICATE-50MG+MAGNESIUM HYDROXIDE-25MG+SIMETHICONE-25MG",
    "image": "digene-tablet.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/otc/digene-tablet",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": false,
    "active": true
  },
  {
    "id": "reddy-becozinc",
    "brandName": "Becozinc",
    "genericName": "B-complex vitamins, vitamin C and zinc",
    "strength": "Multivitamin + zinc",
    "dosageForm": "Capsule",
    "packageSize": "30 capsules",
    "category": "Vitamins",
    "price": 70,
    "mrp": 84.0,
    "manufacturer": "Dr. Reddy's Laboratories Ltd",
    "manufacturerGroup": "Dr. Reddy's",
    "composition": "B-complex vitamins, vitamin C and zinc",
    "image": "becozinc-capsule-30-s.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/otc/becozinc-capsule-30-s",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": false,
    "active": true
  },
  {
    "id": "india-2",
    "brandName": "Ciplox 500",
    "genericName": "Ciprofloxacin",
    "strength": "500 mg",
    "dosageForm": "Tablet",
    "packageSize": "10 tablets",
    "category": "Antibiotics",
    "price": 45,
    "mrp": 54.0,
    "manufacturer": "Cipla Ltd",
    "manufacturerGroup": "Cipla",
    "composition": "CIPROFLOXACIN-500MG",
    "image": "ciplox-500mg-tablet.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/ciplox-500mg-tablet",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "cipla-azee-500-3",
    "brandName": "Azee 500",
    "genericName": "Azithromycin",
    "strength": "500 mg",
    "dosageForm": "Tablet",
    "packageSize": "3 tablets",
    "category": "Antibiotics",
    "price": 75,
    "mrp": 90.0,
    "manufacturer": "Cipla Ltd",
    "manufacturerGroup": "Cipla",
    "composition": "AZITHROMYCIN-500MG",
    "image": "azee-500mg-tablet-3-s.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/azee-500mg-tablet-3-s",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "india-3",
    "brandName": "Cetcip 10",
    "genericName": "Cetirizine",
    "strength": "10 mg",
    "dosageForm": "Tablet",
    "packageSize": "10 tablets",
    "category": "Cold & allergy",
    "price": 20,
    "mrp": 24.0,
    "manufacturer": "Cipla Ltd",
    "manufacturerGroup": "Cipla",
    "composition": "CETIRIZINE-10MG",
    "image": "cetcip-10mg-tablet.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/cetcip-10mg-tablet",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "india-4",
    "brandName": "Asthalin",
    "genericName": "Salbutamol",
    "strength": "100 mcg/dose",
    "dosageForm": "Inhaler",
    "packageSize": "200 metered doses",
    "category": "Respiratory care",
    "price": 170,
    "mrp": 204.0,
    "manufacturer": "Cipla Ltd",
    "manufacturerGroup": "Cipla",
    "composition": "SALBUTAMOL-100MCG",
    "image": "asthalin-inhaler-200mg.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/asthalin-inhaler-200mg",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "cipla-cipladine",
    "brandName": "Cipladine",
    "genericName": "Povidone iodine",
    "strength": "5% w/w",
    "dosageForm": "Ointment",
    "packageSize": "20 g tube",
    "category": "First aid",
    "price": 50,
    "mrp": 60.0,
    "manufacturer": "Cipla Ltd",
    "manufacturerGroup": "Cipla",
    "composition": "POVIDONE IODINE-5%W/W",
    "image": "cipladine-ointment-20gm.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/otc/cipladine-ointment-20gm",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": false,
    "active": true
  },
  {
    "id": "cipla-cofsils-orange",
    "brandName": "Cofsils Orange",
    "genericName": "Amylmetacresol and dichlorobenzyl alcohol",
    "strength": "Orange",
    "dosageForm": "Lozenge",
    "packageSize": "10 lozenges",
    "category": "Cold & allergy",
    "price": 32,
    "mrp": 38.4,
    "manufacturer": "Cipla Health Ltd",
    "manufacturerGroup": "Cipla",
    "composition": "Amylmetacresol and dichlorobenzyl alcohol",
    "image": "cofsils-orange-lozenges.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/otc/cofsils-orange-lozenges",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": false,
    "active": true
  },
  {
    "id": "india-5",
    "brandName": "Omez 20",
    "genericName": "Omeprazole",
    "strength": "20 mg",
    "dosageForm": "Capsule",
    "packageSize": "20 capsules",
    "category": "Digestive care",
    "price": 110,
    "mrp": 132.0,
    "manufacturer": "Dr. Reddy's Laboratories Ltd",
    "manufacturerGroup": "Dr. Reddy's",
    "composition": "OMEPRAZOLE-20MG",
    "image": "omez-20mg-capsule.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/omez-20mg-capsule",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "india-6",
    "brandName": "Razo 20",
    "genericName": "Rabeprazole",
    "strength": "20 mg",
    "dosageForm": "Tablet",
    "packageSize": "15 tablets",
    "category": "Digestive care",
    "price": 240,
    "mrp": 288.0,
    "manufacturer": "Dr. Reddy's Laboratories Ltd",
    "manufacturerGroup": "Dr. Reddy's",
    "composition": "RABEPRAZOLE-20MG",
    "image": "razo-20mg-tablet.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/razo-20mg-tablet",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "india-7",
    "brandName": "Stamlo 5",
    "genericName": "Amlodipine",
    "strength": "5 mg",
    "dosageForm": "Tablet",
    "packageSize": "30 tablets",
    "category": "Heart care",
    "price": 100,
    "mrp": 120.0,
    "manufacturer": "Dr. Reddy's Laboratories Ltd",
    "manufacturerGroup": "Dr. Reddy's",
    "composition": "AMLODIPINE-5MG",
    "image": "stamlo-5mg-tablet-30-s.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/stamlo-5mg-tablet-30-s",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "india-9",
    "brandName": "Nise 100",
    "genericName": "Nimesulide",
    "strength": "100 mg",
    "dosageForm": "Tablet",
    "packageSize": "15 tablets",
    "category": "Pain & fever",
    "price": 120,
    "mrp": 144.0,
    "manufacturer": "Dr. Reddy's Laboratories Ltd",
    "manufacturerGroup": "Dr. Reddy's",
    "composition": "NIMESULIDE-100MG",
    "image": "nise-100mg-tablet.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/nise-100mg-tablet",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "abbott-digene-gel",
    "brandName": "Digene Gel Mint",
    "genericName": "Antacid combination",
    "strength": "Mint",
    "dosageForm": "Oral suspension",
    "packageSize": "200 ml bottle",
    "category": "Digestive care",
    "price": 180,
    "mrp": 216.0,
    "manufacturer": "Abbott India Ltd",
    "manufacturerGroup": "Abbott",
    "composition": "ALUMINIUM HYDROXIDE-830MG+MAGNESIUM HYDROXIDE-185MG+SIMETHICONE-50MG+SODIUM CARBOXYMETHYLCELLULOSE-100MG",
    "image": "digene-gel-mint-syrup-200ml.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/otc/digene-gel-mint-syrup-200ml",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": false,
    "active": true
  },
  {
    "id": "abbott-ensure-vanilla",
    "brandName": "Ensure Vanilla",
    "genericName": "Protein, vitamins and minerals",
    "strength": "Vanilla",
    "dosageForm": "Nutrition powder",
    "packageSize": "375 g jar",
    "category": "Nutrition",
    "price": 640,
    "mrp": 768.0,
    "manufacturer": "Abbott Healthcare Pvt Ltd",
    "manufacturerGroup": "Abbott",
    "composition": "Protein, vitamins and minerals",
    "image": "ensure-vanila-powder-400g.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/otc/ensure-vanila-powder-400g",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": false,
    "active": true
  },
  {
    "id": "abbott-duphalac",
    "brandName": "Duphalac",
    "genericName": "Lactulose",
    "strength": "3.335 g/5 ml",
    "dosageForm": "Oral solution",
    "packageSize": "150 ml bottle",
    "category": "Digestive care",
    "price": 198,
    "mrp": 237.6,
    "manufacturer": "Abbott India Ltd",
    "manufacturerGroup": "Abbott",
    "composition": "LACTULOSE-3.335GM",
    "image": "duphalac-solution-150ml.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/otc/duphalac-solution-150ml",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": false,
    "active": true
  },
  {
    "id": "abbott-thyronorm-50",
    "brandName": "Thyronorm 50",
    "genericName": "Thyroxine sodium",
    "strength": "50 mcg",
    "dosageForm": "Tablet",
    "packageSize": "120 tablets",
    "category": "Thyroid care",
    "price": 130,
    "mrp": 156.0,
    "manufacturer": "Abbott India Ltd",
    "manufacturerGroup": "Abbott",
    "composition": "THYROXINE SODIUM-50MCG",
    "image": "thyronorm-50mcg-tablet.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/thyronorm-50mcg-tablet",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "cipla-ciplox-drops",
    "brandName": "Ciplox Eye/Ear Drops",
    "genericName": "Ciprofloxacin",
    "strength": "0.3% w/v",
    "dosageForm": "Eye/ear drops",
    "packageSize": "10 ml bottle",
    "category": "Eye & ear",
    "price": 16,
    "mrp": 19.2,
    "manufacturer": "Cipla Ltd",
    "manufacturerGroup": "Cipla",
    "composition": "CIPROFLOXACIN-0.3%W/V",
    "image": "ciplox-eye-ear-drops-10ml.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/ciplox-eye-ear-drops-10ml",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  },
  {
    "id": "abbott-gluformin-500",
    "brandName": "Gluformin 500",
    "genericName": "Metformin",
    "strength": "500 mg",
    "dosageForm": "Tablet",
    "packageSize": "10 tablets",
    "category": "Diabetes care",
    "price": 20,
    "mrp": 24.0,
    "manufacturer": "Abbott India Ltd",
    "manufacturerGroup": "Abbott",
    "composition": "METFORMIN-500MG",
    "image": "gluformin-500mg-tablet.jpg",
    "sourceUrl": "https://www.apollopharmacy.in/medicine/gluformin-500mg-tablet",
    "sourceCheckedAt": "2026-09-20",
    "prescriptionRequired": true,
    "active": true
  }
];
