import 'dotenv/config';
import { mkdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { Store } from './store';
import { seed } from './seed';
import { createApp } from './app';
const here=dirname(fileURLToPath(import.meta.url));
const data=resolve(process.env.DATA_DIR||resolve(here,'../data'));
mkdirSync(data,{recursive:true});
const demo=process.env.API_MODE!=='live';
if(!demo&&(!process.env.ADMIN_PASSWORD||!process.env.MEDIA_SECRET||!process.env.OTP_URL?.startsWith('https://')||!process.env.OTP_TOKEN))throw new Error('Live mode requires ADMIN_PASSWORD, MEDIA_SECRET, HTTPS OTP_URL and OTP_TOKEN.');
const bootstrapFile=resolve(data,'local-access.json');
let bootstrap=existsSync(bootstrapFile)?JSON.parse(readFileSync(bootstrapFile,'utf8')):{email:process.env.ADMIN_EMAIL||'owner@oldcity.local',password:process.env.ADMIN_PASSWORD||randomBytes(18).toString('base64url'),secret:process.env.MEDIA_SECRET||randomBytes(32).toString('hex')};
if(!existsSync(bootstrapFile))writeFileSync(bootstrapFile,JSON.stringify(bootstrap,null,2),{mode:0o600});
const store=new Store(resolve(data,'pharmacy.sqlite'));
const savedMode=store.get('meta','mode');
if(savedMode&&savedMode.demo!==demo)throw new Error('Use a separate DATA_DIR when switching between demo and live modes.');
if(!savedMode)store.put('meta',{id:'mode',demo});
seed(store,bootstrap.email,bootstrap.password,demo);
const app=createApp(store,{demo,secret:process.env.MEDIA_SECRET||bootstrap.secret,origins:(process.env.CORS_ORIGINS||'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8084,http://localhost:8087,http://localhost:8089').split(','),assets:resolve(here,'../../mobile/assets'),otpUrl:process.env.OTP_URL,otpToken:process.env.OTP_TOKEN});
const port=Number(process.env.PORT||4000),host=process.env.HOST||'127.0.0.1';
app.listen(port,host,()=>{console.log(`Pharmacy API ready at http://${host}:${port} (${demo?'shared demo data':'live'}).`);if(demo)console.log('Local dashboard sign-in is saved in '+bootstrapFile);});
