import { StyleSheet } from "react-native";
export const colors = {
  primary: "#00695C",
  primaryDark: "#004D40",
  mint: "#C9E8DF",
  background: "#F0F4F2",
  white: "#FFFFFF",
  text: "#142E29",
  muted: "#4D635D",
  border: "#C5D7CF",
  amber: "#815018",
  amberLight: "#FFF3DD",
  red: "#A52D35",
  blue: "#D3E3EF",
};
export const space = { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32 };
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  content: { padding: space.lg, gap: space.lg, paddingBottom: 32, width: "100%", maxWidth: 600, alignSelf: "center" },
  row: { flexDirection: "row", alignItems: "center", gap: space.md },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.md,
  },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: space.sm },
  grow: { flex: 1 },
  card: {
    padding: space.lg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    gap: space.md,
  },
  hero: {
    backgroundColor: colors.primaryDark,
    borderRadius: 12,
    padding: space.xl,
    gap: space.lg,
  },
  title: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.6,
  },
  heading: {
    fontSize: 18,
    lineHeight: 25,
    fontWeight: "700",
    color: colors.text,
  },
  text: { fontSize: 15, lineHeight: 22, color: colors.text },
  small: { fontSize: 12, lineHeight: 18, color: colors.muted },
  label: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
    color: colors.text,
  },
  white: { color: colors.white },
  muted: { color: colors.muted },
  input: {
    minHeight: 54,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: space.lg,
    paddingVertical: space.md,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.white,
  },
  button: {
    minHeight: 54,
    borderRadius: 16,
    paddingHorizontal: space.lg,
    paddingVertical: space.md,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: space.sm,
    backgroundColor: colors.primary,
  },
  buttonText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
  },
  secondary: {
    backgroundColor: colors.mint,
    borderWidth: 1,
    borderColor: colors.border,
  },
  secondaryText: { color: colors.primaryDark },
  disabled: { opacity: 0.45 },
  badge: {
    alignSelf: "flex-start",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: colors.mint,
  },
  badgeText: { fontSize: 13, fontWeight: "600", color: colors.primaryDark },
  warning: { backgroundColor: colors.amberLight },
  error: { color: colors.red, fontSize: 16, lineHeight: 24 },
  notice: {
    backgroundColor: colors.mint,
    padding: space.lg,
    borderRadius: 12,
    gap: space.sm,
  },
  photo: {
    width: "100%",
    height: 250,
    borderRadius: 16,
    backgroundColor: colors.mint,
  },
  avatar: {
    width: 72,
    height: 80,
    borderRadius: 16,
    backgroundColor: colors.mint,
  },
  medicineIcon: {
    width: 66,
    height: 76,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.mint,
  },
  chip: {
    minHeight: 48,
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  section: { gap: space.md },
  centered: {
    alignItems: "center",
    justifyContent: "center",
    padding: space.xl,
    gap: space.lg,
  },
  divider: { height: 1, backgroundColor: colors.border },
});
